Add --output_base_suffix as startup option
bazelbuild/bazel pull request #11348
Opened 2020-05-10 23:00 UTC by moroten

Simplify how to specify an output_base parallel to the default one or the output_base specified in the user .bazelrc file. Use case include using different `--output_base_suffix` depending on configuration to avoid discarding the analysis cache or to avoid interrupting a long running test.

I know this patch does not contain any tests, which of course is needed if this should be merged at all. 

To start with, is this a reasonable feature to add?

2020-05-13 04:28 UTC, aiuto commented
Please start with an issue describing the feature and we can debate a design there.

2020-05-18 21:39 UTC, moroten commented
@aiuto Thank you for your reply. I've created #11435, so please close this PR if you prefer to keep the list of open PRs short.

2020-05-19 02:15 UTC, aiuto commented
Thanks for creating the issue. We can leave this alive. I'll mark it WIP so we don't keep trying to assign a reviewer right now.

2020-09-23 14:30 UTC, philwo commented
@moroten I think this is a useful change with localized impact - would you mind adding a test, then I'd go ahead and merge this. :)

2020-09-23 14:36 UTC, philwo requested changes
Could you please add the startup flag to the Java code, too, similar to this one :https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/runtime/BlazeServerStartupOptions.java;l=132?q=%5C%22output_user_root&ss=bazel

That ensures it's documented and shows up in the help :)

2020-09-23 14:36 UTC, philwo commented on src/main/cpp/startup_options.h
> +  // Suffix to append to Blaze's output base, e.g. `-extra` or `/../no-hash`.
Could you change "append" to "path-append" to make it clear the resulting string will be post-processed into a valid normalized and absolute path?

2020-09-23 14:36 UTC, philwo commented on src/main/cpp/startup_options.h
> +  // Suffix to append to Blaze's output base, e.g. `-extra` or `/../no-hash`.
Oh, and we should absolutely test for these `/../no-hash` up-references in the tests for this 😄

2020-09-28 08:13 UTC, moroten commented
I will eventually work on this, but it might take some weeks until I find time as this feature is no high priority for me.

2020-11-10 17:27 UTC, philwo commented
We're replacing the "WIP" label with the native GitHub "draft PRs". I thus converted this PR to a draft.

Please mark this as ready for review when it's ready, or close it if you no longer intend to work on it. Thanks! 👍

2021-03-03 11:23 UTC, moroten commented
Will not have time to do it in any near future. Therefore, closing.

2021-03-03 11:23 UTC, closed without merging