Enable coverage for generated source files
bazelbuild/bazel pull request #11350
Opened 2020-05-11 08:53 UTC by Rasrack

Currently generated source files can't be included in the coverage report. Remove the check to enable coverage for the generated files.

2020-05-13 04:30 UTC, aiuto commented
Please create an issue for this first so more people can review the relative merits of the feature and if/how it should be done.  I strongly suspect that this change would be contentious as is.

2020-05-13 04:47 UTC, keith commented
+1 I think this would be interesting for our use case, but I'm not sure we'd want it by default, and ideally there would be some way to disable it.

2020-05-13 04:52 UTC, Rasrack commented
Created the issue #11375

2020-05-14 03:47 UTC, jin commented
Also reported on Slack: https://bazelbuild.slack.com/archives/CA31HN1T3/p1588710579121400

2021-11-03 10:07 UTC, ozio85 commented
+1 This is essential for coverage to work; this should absolutely be enabled by default. Maybe it is a bug in isSourceArtifact, but I think that check is not needed.

Currently this blocks us using the Bazel release as-is

2021-11-03 10:10 UTC, ozio85 commented
@meteorcloudy is it possible to merge this?

2021-11-03 11:01 UTC, c-mita commented
I'm wary of merging, at least right now. Internally, we have tools that expect to be able to open files referenced in coverage reports which would not be possible if they don't exist in the repo.

Either we would need to guard this feature behind a yet-another-flag or any such tool has to be able to handle files not existing in the repo.

2021-11-03 13:00 UTC, ozio85 commented
I get it.. but this sounds like a report generator issue, not that the coverage data should avoid source files. That seems dangerous to me.

We do extra filtering on the coverage.dat file to e.g. exclude parts of debug frameworks, but that is an intermediate step, and not something we would consider on the raw output.

2022-12-16 10:45 UTC, oquenchil commented
@c-mita Can this be closed?

2022-12-16 11:44 UTC, c-mita commented
> @c-mita Can this be closed?

Not quite; I want to check what happens with proto_library in the new year before it's dismissed. There was interest expressed in this PR to me at Bazelcon.

2022-12-16 16:12 UTC, limdor commented
I can also say that this would be interesting for us.

2023-01-20 15:05 UTC, c-mita commented
I can imagine supporting this feature under an experimental flag for the moment; the cost to doing so doesn't seem high to me.

2023-01-20 15:16 UTC, c-mita requested changes
Guard with an experimental flag (e.g. --experimental_collect_coverage_for_generated_files).

2023-02-03 09:55 UTC, oquenchil commented
@c-mita  are you waiting for a user response, if so can you change the label from awaiting-review to awaiting-user-response to reflect that?

2023-03-11 16:50 UTC, Rasrack commented
@c-mita I added the experimental flag as per review comments

2023-03-17 09:07 UTC, c-mita approved these changes
LGTM.

I was going to ask for a test, but in investigating how best to do it, I ended up writing it so I'll just add it in myself when I import.

2023-03-17 09:11 UTC, fmeum commented
@c-mita Not entirely sure whether it's relevant for this particular flag, but this may lack a line in `CoreOptions#getExec` to carry it over to the exec configuration.

2023-03-17 09:56 UTC, c-mita commented
> @c-mita Not entirely sure whether it's relevant for this particular flag, but this may lack a line in `CoreOptions#getExec` to carry it over to the exec configuration.

I don't that matters since, AFAIU, this shouldn't be carried over to the exec configuration. The other coverage flags aren't carried over either.

2023-03-17 12:30 UTC, c-mita commented
> LGTM.
> 
> I was going to ask for a test, but in investigating how best to do it, I ended up writing it so I'll just add it in myself when I import.

Actually, i couldn't even ask you to write tests; the tests for InstrumentedFilesCollector haven't been open-sourced for some reason...

2023-03-24 08:38 UTC, sgowroji commented
Hi @c-mita, Since I can see that this PR has been approved, please let me know whether I should proceed with importing it. Thanks!

2023-03-24 10:19 UTC, c-mita commented
I've done the import myself and it's currently undergoing internal review.

2023-05-15 19:33 UTC, limdor commented
@c-mita could you please provide an update on this? Is it still under internal review? Thanks

2023-06-11 18:33 UTC, UebelAndre commented
@c-mita friendly ping 😄

2023-06-12 14:47 UTC, closed without merging

2023-06-12 14:55 UTC, UebelAndre commented
Thank you! Is there any work needed to get this in the upcoming Bazel 6.3 release?

2023-06-12 15:01 UTC, c-mita commented
@bazel-io fork 6.3.0

2023-06-13 21:41 UTC, iancha1992 commented
> Thank you! Is there any work needed to get this in the upcoming Bazel 6.3 release?

@UebelAndre Here is the PR to push this change to the 6.3.0 just for your reference: https://github.com/bazelbuild/bazel/pull/18664

Also, just for your reference, here is the list of the issues/PR's that shall be resolved for the 6.3.0 release: https://github.com/bazelbuild/bazel/milestone/53

Thanks