Arm64 installation instructions
bazelbuild/bazel pull request #12232
Opened 2020-10-08 17:04 UTC by mattsplats

See https://github.com/bazelbuild/bazel/issues/11994.

Looks like a simple note is all that's needed now for installing on Ubuntu.

Also, I noticed the Fedora/CentOS instructions don't work on Amazon Linux 2, so I added a reference to Bazelisk - let me know what you think. Could call out AL2 specifically.

2020-10-08 17:08 UTC, mattsplats commented
@googlebot I signed it!

2020-10-09 03:08 UTC, aiuto requested changes

2020-10-09 03:08 UTC, aiuto commented on site/docs/install-redhat.md
> +Baz[The Bazelisk installer](install-bazelisk.md) is an alternative to package installation.
Baz?

2020-10-09 16:05 UTC, gregestren commented
I want to give @philwo a chance to comment re: https://github.com/bazelbuild/bazel/issues/11994#issuecomment-703685485 but otherwise lgtm and I'd be happy to merge.

2020-10-09 16:08 UTC, philwo commented
@gregestren @mattsplats Thank you!

2020-10-09 20:52 UTC, closed without merging