Starlark: dict.popitem without hashmap lookup
bazelbuild/bazel pull request #12513
Opened 2020-11-18 22:54 UTC by stepancheg

Benchmarks becomes about 7% faster.

Not critical optimization, since Starlark doesn't have a while loop,
but still better have it fixed.

Also removes unused `StarlarkThread` parameter.

2020-11-26 15:30 UTC, alandonovan requested changes

2020-11-26 15:30 UTC, alandonovan commented on src/main/java/net/starlark/java/eval/Dict.java
>                + "<code>popitem()</code> is useful to destructively iterate over a dictionary, "
Let's change this comment to say "the first", not "an arbitrary", as that's what the spec requires:
 https://github.com/bazelbuild/starlark/blob/master/spec.md#dict%C2%B7popitem

2020-11-26 17:13 UTC, stepancheg commented
Updated the doc.

2020-11-26 17:35 UTC, alandonovan approved these changes

2020-11-30 23:33 UTC, alandonovan commented
(cr/344900319)

2020-12-01 17:54 UTC, closed without merging