Include the product version as an alias when generating xcode_version targets
bazelbuild/bazel pull request #12563
Opened 2020-11-26 01:19 UTC by segiddins

This allows passing `--xcode_version=$XCODE_PRODUCT_BUILD_VERSION` in the context of an Xcode shell script build phase

2020-11-26 01:20 UTC, keith approved these changes

2020-11-30 17:08 UTC, susinmotion approved these changes

2020-11-30 20:30 UTC, tetromino requested changes
This change is of course better than the broken check we had before, but it still doesn't match the comments and variable names; "at least as large" means version >= subversion, i.e. !(subversion > version), but your new check is for subversion < version.

Please change to

      BOOL atLeastAsLarge =
          ([subversionEntry.version compare:entry.version
                                    options:NSNumericSearch] != NSOrderedDescending);

2020-12-01 01:15 UTC, segiddins commented
@tetromino good catch, done

2020-12-01 15:18 UTC, tetromino approved these changes

2020-12-04 23:01 UTC, closed without merging