ijar: fix manifest sections handling
bazelbuild/bazel pull request #12771
Opened 2021-01-04 14:43 UTC by liucijus

Fixes #12730 

Important changes:
 - removed line stripping from the original implementation
 - label/rule attributes are appended after main attributes, then the rest of the `MANIFEST.MF` content is appended - this way sections data is preserved.

2021-01-11 18:23 UTC, ittaiz commented
@cushon wdyt? Rather small PR which could help us out at rules_scala

2021-01-22 08:38 UTC, ittaiz commented
Can anyone help with this? @liucijus stepped up and not only reported the issue but also sent a small PR and it's just sitting here.
FYI we're copy ~25k LOC into rules scala to be unblocked.
Divergences are happening :(

2021-01-29 06:18 UTC, ittaiz commented
@aiuto process wise and bazel community- how long should a community contributor wait before getting a review? Especially for a small and confined PR?
I'm asking because this is demoralizing and works against your efforts of having not only Google look out for Bazel

2021-01-29 07:52 UTC, comius requested changes
LGTM, except that I would like to also have a test where Target-Label is in the manifest with sections and it is skipped.

2021-01-29 07:52 UTC, comius commented on third_party/ijar/test/BUILD
> +    srcs = ["jar-with-manifest-sections.jar"],
For reference:
```
Archive:  jar-with-manifest-sections.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
     1382  2010-01-01 05:00   AnnotatedClass.class
      476  2010-01-01 05:00   Annotations.class
      381  2010-01-01 05:00   Annotations$ParametersOnlyAnnotation.class
      468  2010-01-01 05:00   Annotations$RuntimeInvisible.class
      561  2010-01-01 05:00   Annotations$RuntimeVisible.class
        0  2010-01-01 05:00   META-INF/
       96  2021-01-04 09:23   META-INF/MANIFEST.MF
       19  2018-03-29 15:53   textfile.txt
---------                     -------
     3383                     8 files
```

```
$ cat META-INF/MANIFEST.MF 
Manifest-Version: 1.0
Created-By: test-code

Name: foo
Foo: bar

Name: baz
Another: bar
```

2021-01-29 07:53 UTC, comius commented
@cushon, do you think this could have any impact on the other Java code? My best guess is that it doesn't, because before the patch manifests with sections would just get mangled.

2021-01-29 08:28 UTC, comius approved these changes

2021-01-29 08:28 UTC, comius commented on third_party/ijar/test/BUILD
> +    srcs = ["jar-with-target-label-and-manifest-sections.jar"],
For reference:
```
Archive:  jar-with-target-label-and-manifest-sections.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
     1382  2010-01-01 05:00   AnnotatedClass.class
      476  2010-01-01 05:00   Annotations.class
      381  2010-01-01 05:00   Annotations$ParametersOnlyAnnotation.class
      468  2010-01-01 05:00   Annotations$RuntimeInvisible.class
      561  2010-01-01 05:00   Annotations$RuntimeVisible.class
        0  2010-01-01 05:00   META-INF/
      122  2021-01-29 08:19   META-INF/MANIFEST.MF
       19  2018-03-29 15:53   textfile.txt
---------                     -------
     3409                     8 files
```

```
$ cat META-INF/MANIFEST.MF 
Manifest-Version: 1.0
Created-By: test-code
Target-Label: //not:this

Name: foo
Foo: bar

Name: baz
Another: bar
```

2021-01-29 08:46 UTC, comius commented
Internal linter says: ".jar files are no longer allowed in third_party." and prevents me from adding new .jar file (while old ones are fine). Bazel should be able to generate those .jars from sources, but it's another curve ball.

2021-01-29 08:57 UTC, liucijus commented
> LGTM, except that I would like to also have a test where Target-Label is in the manifest with sections and it is skipped.

I assume you want a test to show that existing label is update, right. If I'm not missing anything, it's the way ijar works.

2021-01-29 09:20 UTC, comius commented
> > LGTM, except that I would like to also have a test where Target-Label is in the manifest with sections and it is skipped.
> 
> I assume you want a test to show that existing label is update, right? If I'm not missing anything, it's the way ijar works.

Correct. I already reviewed it, it's ok.

2021-01-29 09:37 UTC, comius commented
> Internal linter says: ".jar files are no longer allowed in third_party." and prevents me from adding new .jar file (while old ones are fine). Bazel should be able to generate those .jars from sources, but it's another curve ball.

Do you have resource/will to fix this as well?

2021-01-29 10:39 UTC, liucijus commented
> > Internal linter says: ".jar files are no longer allowed in third_party." and prevents me from adding new .jar file (while old ones are fine). Bazel should be able to generate those .jars from sources, but it's another curve ball.
> Do you have resource/will to fix this as well?

I'll look into it

2021-01-29 20:35 UTC, liucijus commented
> > > Internal linter says: ".jar files are no longer allowed in third_party." and prevents me from adding new .jar file (while old ones are fine). Bazel should be able to generate those .jars from sources, but it's another curve ball.
> > > Do you have resource/will to fix this as well?
> 
> I'll look into it

Done

2021-02-01 12:19 UTC, closed without merging

2021-02-01 13:44 UTC, ittaiz commented
Thanks @liucijus and @comius!