Expose java stub template through @bazel_tools
bazelbuild/bazel pull request #12994
Opened 2021-02-11 10:20 UTC by illicitonion

Currently rules_kotlin downloads this via raw.githubusercontent.com:

https://github.com/bazelbuild/rules_kotlin/blob/96c70d1d3cc788b03406f7db6a659c78d311c3d8/kotlin/internal/repositories/release_repositories.bzl#L55-L62

https://github.com/bazelbuild/rules_kotlin/blob/96c70d1d3cc788b03406f7db6a659c78d311c3d8/kotlin/internal/jvm/jvm.bzl#L135-L138

This will allow rules_kotlin to point at a file from Bazel proper,
rather than downloading it via the internet.

2021-04-08 11:23 UTC, comius requested changes
I don't mind exposing the template, just the implementation of it.

Is it possible to move the java_stub_template.txt file into the tools/java/ directory and then depend on it from rules/java? This way there would be no need for a copy genrule.

2021-04-08 15:06 UTC, illicitonion commented
Absolutely - done! This is now exposed as `@bazel_tools//tools:java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt` without any copies - thanks for taking a look :)

2021-04-08 16:27 UTC, comius commented
> Absolutely - done! This is now exposed as `@bazel_tools//tools:java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt` without any copies - thanks for taking a look :)

Do you need the whole path? I thought you could put it to tools/jdk package directly.

2021-04-08 16:46 UTC, illicitonion commented
> > Absolutely - done! This is now exposed as `@bazel_tools//tools:java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt` without any copies - thanks for taking a look :)
> 
> Do you need the whole path? I thought you could put it to tools/jdk package directly.

If I do that, when I reference it as a `resources` it ends up in the root of the jar, rather than in the package, and that makes the `ResourceFileLoader` sad. I could side-step `ResourceFileLoader` to not do the package-name-prefixing when trying to read the file, if you'd prefer?

2021-04-09 05:44 UTC, comius commented
> > > Absolutely - done! This is now exposed as `@bazel_tools//tools:java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt` without any copies - thanks for taking a look :)
> > 
> > 
> > Do you need the whole path? I thought you could put it to tools/jdk package directly.
> 
> If I do that, when I reference it as a `resources` it ends up in the root of the jar, rather than in the package, and that makes the `ResourceFileLoader` sad. I could side-step `ResourceFileLoader` to not do the package-name-prefixing when trying to read the file, if you'd prefer?

No sidestepping `ResourceFileLoader` doesn't seem nice. Can `filegroup` rule help in this case (with `path`)? Or even with the previous version you had with the file in original location, i.e. replacing genrule with filegroup?

2021-04-09 10:48 UTC, illicitonion commented
Filegroup doesn't appear to have a `path` attribute? https://docs.bazel.build/versions/master/be/general.html#filegroup

2021-04-09 11:14 UTC, comius commented
> Filegroup doesn't appear to have a `path` attribute? https://docs.bazel.build/versions/master/be/general.html#filegroup

Sorry, you're right.

2021-04-09 11:16 UTC, illicitonion commented
Would you rather I fix up CI for this version, or go back to a genrule which does `cp`? (Or something else :))

2021-04-09 11:26 UTC, comius commented
> Would you rather I fix up CI for this version, or go back to a genrule which does `cp`? (Or something else :))

I'd like to have "pretty" code, but I don't have time to play around myself to figure out if there is something nicer.

I'll accept the genrule with 'cp'. This way you don't have to deal with peculiarities of the tests and other options like creating out of place directory structure or tinkering with ResourceFileLoader seem worse.

I don't know by heart if you could use a regular `filegroup` instead of  `cp genrule` in the old version of the code. If you are willing to try; otherwise it's fine too.

2021-04-09 12:42 UTC, illicitonion commented
I played around with `filegroups` for a while to no effect - reverted to the original `cp` approach

2021-04-09 12:46 UTC, comius approved these changes

2021-04-09 12:47 UTC, comius commented
> I played around with `filegroups` for a while to no effect - reverted to the original `cp` approach

Thanks!

2021-04-16 11:48 UTC, closed without merging