ctexplain: make cquery parsing more robust
bazelbuild/bazel pull request #13212
Opened 2021-03-12 19:05 UTC by gregestren

Specifically:

 - Handle labels with spaces
 - Handle targets with no fragment requirements.

These were both inspired by real analyses.

Testing: `$ bazel test //tools/ctexplain:all`
Work towards #10613

2021-04-01 20:57 UTC, sdtwigg requested changes

2021-04-01 20:57 UTC, sdtwigg commented on tools/ctexplain/bazel_api.py
> +      fragments = tuple(line[fragments_start + 1:fragments_end].split(", "))
tuple(x.strip() for x in line[fragments_start + 1:fragments_end].split(","))

is a little more resilient to whitespace changes.

2021-04-01 20:57 UTC, sdtwigg commented on tools/ctexplain/bazel_api.py
> +  fragments_start = line.find("[", config_hash_end)
move under the else: condition below; after verifying not in null configuration

2021-04-01 20:57 UTC, sdtwigg commented on tools/ctexplain/bazel_api_test.py
> +    self.assertEqual(len(cts), 1)
assertLen

2021-04-01 20:57 UTC, sdtwigg commented on tools/ctexplain/bazel_api_test.py
> +    self.assertEqual(len(cts), 1)
assertLen

2021-04-01 20:57 UTC, sdtwigg commented on tools/ctexplain/bazel_api_test.py
> +    self.assertEqual(len(cts[0].transitive_fragments), 0)
assertEmpty

2022-12-07 16:27 UTC, keertk commented
Hi all, we're doing a clean up of old PRs and will be closing this one since it seems to have stalled. Please feel free to reopen if you’re still interested in pursuing this.

2022-12-07 16:27 UTC, closed without merging