Handle java versions with a single component
bazelbuild/bazel pull request #13407
Opened 2021-04-27 01:55 UTC by keith

Fixes https://github.com/bazelbuild/bazel/issues/13406

2021-04-27 05:34 UTC, keith commented
@comius can you review?

2021-04-27 11:56 UTC, comius requested changes
Can you add a test to src/test/shell/bazel/bazel_with_jdk_test.sh?

2021-04-28 01:02 UTC, keith commented
Updated!

2021-04-28 06:04 UTC, comius approved these changes

2021-04-28 07:51 UTC, closed without merging