Report message from remote on status failure
bazelbuild/bazel pull request #13788
Opened 2021-08-02 15:15 UTC by illicitonion

If the remote has useful debugging information, it's more useful to show
it than discard it.

2021-08-02 15:15 UTC, illicitonion commented
/cc @coeuvre

2021-08-03 02:51 UTC, coeuvre requested changes
Thanks for the PR!

Can you please add a test in `RemoteSpawnRunnerTest`?

2021-08-03 14:37 UTC, illicitonion commented
Added the test - thanks!

2021-08-04 01:14 UTC, coeuvre approved these changes
Thanks! Importing.

2021-08-04 08:43 UTC, closed without merging