feat: add extra fields to flags proto
bazelbuild/bazel pull request #14015
Opened 2021-09-20 14:44 UTC by mattem

Adds three extra fields to the `bazel_flags` proto to allow fetching the option effects and metadata tags, and associated documentation category when calling `bazel help flags-as-proto`. 

These extra fields can be useful if programmatically parsing and displaying flag documentation (ie, in an IDE plugin etc)

2021-09-24 21:11 UTC, mattem commented
I couldn't see existing test coverage for `flags-as-proto`, but happy to add some as needed

2021-09-24 22:44 UTC, alexeagle commented
This looks really useful, @aiuto any idea who's the best reviewer for this area?

2021-10-05 04:36 UTC, aiuto commented
@alexeagle We have a rotation for github issue triage so they can be assigned to the right team and/or reviewer. @oquenchil gave it to configurability, which seems about right.

2021-11-30 16:50 UTC, aiuto commented
@mattem:  I rewrote the PR description to be a little more precise. PTAL.

@brandjon: Please take a quick look to see if you have any concerns w.r.t. StarDoc.
@comius: FYI

2021-11-30 16:50 UTC, aiuto requested changes

2021-11-30 16:50 UTC, aiuto commented on src/main/java/com/google/devtools/build/lib/runtime/commands/HelpCommand.java
> +        !OptionDocumentationCategory.UNCATEGORIZED.equals(option.getDocumentationCategory())) {
Please also drop UNDOCUMENTED

2021-11-30 16:50 UTC, aiuto commented on src/main/java/com/google/devtools/build/lib/runtime/commands/HelpCommand.java
> +    flagBuilder.addAllMetadataTags(optionMetadataTags);
Please drop OptionMetadataTag.INTERNAL

2021-12-07 19:03 UTC, aiuto requested changes
Please try not to force push. github seems to lose the ability to diff since the last commit, making review harder.

2021-12-07 19:03 UTC, aiuto commented on src/main/java/com/google/devtools/build/lib/runtime/commands/HelpCommand.java
> +        .filter(tag -> OptionMetadataTag.INTERNAL.equals(tag))
Is this backwards?  Won't that drop everything except INTERNAL?

2021-12-08 01:33 UTC, aiuto reviewed
I've been thinking about this, and perhaps my requests don't make sense.  If that is true, I apologize for the needless work.   It's not that we don't want to add the UNDOCUMENTED and INTERNAL tags to the proto. Instead we should not generate any output for the internal tags.

Do you have a before and after sample that can show the impact of the change? My hunch is that you won't see anything that is undocumented in the first place, in which case, not setting the tag doesn't do anything useful.  I don't necessarily need a test, just a statement in the PR description that we aren't emitted docs for the undocumented flags.  If we *are* doing that, then we have a different problem.

2022-01-23 02:30 UTC, aiuto commented
Any thoughts?

2022-01-23 18:38 UTC, mattem commented
Sorry dropped the ball here. I see what you are saying. So taking a look at the raw proto out, we don't get any `INTERNAL` flags through if we remove the filtering, but we do get `UNCATEGORIZED` and `UNDOCUMENTED` flags in the proto.

With the filtering removed:
```
1 {
  1: "experimental_incremental_dexing_after_proguard"
  2: 0
  3: "Whether to use incremental dexing tools when building proguarded Android binaries.  Values > 0 turn the feature on, values > 1 run that many dexbuilder shards."
  4: "aquery"
  4: "build"
  4: "canonicalize-flags"
  4: "clean"
  4: "config"
  4: "coverage"
  4: "cquery"
  4: "info"
  4: "mobile-install"
  4: "print_action"
  4: "run"
  4: "test"
  6: 0
  7: "LOADING_AND_ANALYSIS"
  7: "LOSES_INCREMENTAL_STATE"
  9: "UNDOCUMENTED"
}
```

Vs still getting the flag though but without the tags:

```
1 {
  1: "experimental_incremental_dexing_after_proguard"
  2: 0
  3: "Whether to use incremental dexing tools when building proguarded Android binaries.  Values > 0 turn the feature on, values > 1 run that many dexbuilder shards."
  4: "aquery"
  4: "build"
  4: "canonicalize-flags"
  4: "clean"
  4: "config"
  4: "coverage"
  4: "cquery"
  4: "info"
  4: "mobile-install"
  4: "print_action"
  4: "run"
  4: "test"
  6: 0
  7: "LOADING_AND_ANALYSIS"
  7: "LOSES_INCREMENTAL_STATE"
}
```

Can remove them from the output by filtering above:

```
--- a/src/main/java/com/google/devtools/build/lib/runtime/commands/HelpCommand.java
+++ b/src/main/java/com/google/devtools/build/lib/runtime/commands/HelpCommand.java
@@ -244,7 +244,9 @@ public final class HelpCommand implements BlazeCommand {
     BiConsumer<String, OptionDefinition> visitor =
         (commandName, option) -> {
           if (ImmutableSet.copyOf(option.getOptionMetadataTags())
-              .contains(OptionMetadataTag.INTERNAL)) {
+              .contains(OptionMetadataTag.INTERNAL) ||
+              OptionDocumentationCategory.UNDOCUMENTED.equals(option.getDocumentationCategory()) ||
+              OptionDocumentationCategory.UNCATEGORIZED.equals(option.getDocumentationCategory())) {
             return;
           }
           BazelFlagsProto.FlagInfo.Builder info =
```

Let me know if that's the desired state.

2022-01-26 17:27 UTC, aiuto commented
UNCATEGORIZED should obviously be output.
I think it is fine to emit UNDOCUMENTED flags, as long as you are emitting the tag too.
That way the renderer can choose what to do.  Either mark them *undocumented* or drop them entirely.

2022-02-11 13:48 UTC, mattem commented
Okay, so I think the latest commit has the behaviour we are going for. It will completely drop `INTERNAL` flags from the proto (existing behaviour), but will keep both `UNDOCUMENTED` and `UNCATEGORIZED` flags but will always tag them as such, as therefore left up to the consumer to decide how to present them.

2022-02-11 14:49 UTC, aiuto approved these changes

2022-02-11 14:52 UTC, aiuto commented
I'll start a merge.

2022-02-11 16:00 UTC, closed without merging