Make cpp assembly file extensions case sensitive again
bazelbuild/bazel pull request #14131
Opened 2021-10-19 07:59 UTC by Gormo

This fixes an issue introduced by PR #14005 where .s and .S
extensions were handled case-insensitive on Windows so the action
assemble was triggered instead of preprocess_assemble.

2021-11-08 10:44 UTC, Gormo commented
@lberki, can we merge this so we don't need to maintain this patch locally when doing uplifts?

2021-11-08 10:51 UTC, oquenchil commented
@buildbreaker2021 will take over the review and import.

2021-11-09 11:00 UTC, buildbreaker2021 requested changes

2021-11-09 14:59 UTC, Gormo commented on src/main/java/com/google/devtools/build/lib/rules/cpp/CppFileTypes.java
> +  public static final FileType ASSEMBLER_WITH_C_PREPROCESSOR =
Good point.. I've reverted that part.

2021-11-09 14:59 UTC, Gormo commented on src/main/java/com/google/devtools/build/lib/rules/cpp/CppFileTypes.java
> +  public static final FileType PIC_ASSEMBLER =
Test added!

2021-11-09 15:09 UTC, buildbreaker2021 approved these changes
lgtm

2021-11-11 07:28 UTC, comius requested changes
This PR seems to negate the assumptions made in WindowsOsPathPolicy.endsWith, that Windows don't know about character case (upper/lower). https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/vfs/WindowsOsPathPolicy.java;l=213;drc=9cb59369a84d9328c2929eefcb58c1b972ab15f2

Having a special case for Windows in CppFileTypes introduces a tech debt in my opinion - there's lack of comments (in this PR) why this there is a need for a special case here. Please add a comment with a link to an issue.

I think the right thing to do is to remove the assumption (of case insensitivity) in WindowsOsPathPolicy and then fix the locations where poorly behaved toolchains create either lower or upper cased suffices.

2021-11-15 14:18 UTC, torgil commented
> I think the right thing to do is to remove the assumption (of case insensitivity) in WindowsOsPathPolicy and then fix the locations where poorly behaved toolchains create either lower or upper cased suffices.

This would reintroduce the issues in #14005. The "right thing" question in there was never properly discussed but you could reason that a new windows user would have a hard time to "fix" third-party libraries for casing (Microsoft clibs package in my case) or make Windows-specific case-by-case addition to CppFileTypes.

2021-11-15 14:59 UTC, comius commented
> > I think the right thing to do is to remove the assumption (of case insensitivity) in WindowsOsPathPolicy and then fix the locations where poorly behaved toolchains create either lower or upper cased suffices.
> 
> This would reintroduce the issues in #14005. The "right thing" question in there was never properly discussed but you could reason that a new windows user would have a hard time to "fix" third-party libraries for casing (Microsoft clibs package in my case) or make Windows-specific case-by-case additions to CppFileTypes.

Sure, I agree.

Would you mind just adding a comment to the code, that "FileType is extended to use case-sensitive comparison also on Windows". I don't want the next developer hitting their head on it.

When this piece of code is rewritten to Starlark, we won't have the luxury of extending FileType, all file types will need to be listed case-sensitively. Perhaps special cased for linux/windows/macos one level higher.

I'm not sure if it's a good or a bad news we only need to special case this one special operating system :)

2021-11-15 20:19 UTC, comius approved these changes

2021-11-23 06:44 UTC, Gormo commented
Ok for merge now?

2021-11-24 10:39 UTC, closed without merging

2022-07-27 07:09 UTC, fmeum commented
@bazel-io flag