fix(#14137): s/ '#!/bin/bash' / '#!/usr/bin/env bash'
bazelbuild/bazel pull request #14138
Opened 2021-10-20 00:09 UTC by yesudeep

Fixes: https://github.com/bazelbuild/bazel/issues/14137

2022-05-19 20:11 UTC, ted-xie requested changes
This PR is too huge; there are 300+ files here and even loading the diff actually causes my browser to stutter. Please break this up into sub-PRs (maybe alphabetically, with ~10 files changed per PR) if this is still affecting you. Breaking it up into sub-PRs will also help the debug/rollback process if changing the shebangs cause any issues (which should not be the case, but you never know).

Also worth noting that public Google style guides prefer `#!/bin/bash` as the GNU bash shebang. See here: https://chromium.googlesource.com/chromiumos/docs/+/HEAD/styleguide/shell.md#standard-selection

I'm not saying we have to treat the Chromium shell style guide as the golden truth, but there is precedent to use `#!/bin/bash`. I can imagine that keeping shell versions in sync for developer environments is the main reason for this, at least internally. For external-facing projects such as Bazel, I can see some benefit to allowing for the more flexible `#!/usr/bin env bash` style.

2022-05-19 20:13 UTC, ted-xie commented
Please also provide a less esoteric commit message. I would imagine most Bazel users are familiar with the sed-style regex syntax, but something straightforward like `Replace all shebangs with #!/usr/bin/env bash` would be a lot easier to read and understand at a glance.

2022-05-19 20:40 UTC, ted-xie commented
Some more thoughts on this:

Is there a reason to change _every_ shebang in every shell script? I think only a subset of these scripts are directly executed in a way that the shebang even matters (such as `./a/b/c/d.sh`). Maybe there's something we can change in the job orchestrator that transcends the problem altogether.

2022-05-19 20:45 UTC, aiuto commented
I suggest breaking the work along clear boundaries rather than by size or name.

- get bazel to dist-build
- get tests to run
- the long tail of other stuff.

2022-06-16 06:38 UTC, sgowroji commented
Hello @yesudeep, Could you please respond to the above [comments](https://github.com/bazelbuild/bazel/pull/14138#issuecomment-1132192936) and resolve the conflicts. Thanks!

2022-08-11 09:03 UTC, aiuto commented on src/main/native/windows/build_windows_jni.sh
> -#!/bin/bash -eu
I'm not sure this is right for scripts that only run on windows.

2022-08-11 09:14 UTC, aiuto commented
From the conversation thread, it is pretty clear we should just close this PR and try again in a more disciplined way.

2022-08-11 09:14 UTC, closed without merging