Add incompatible flag to disable cfg="host" from Starlark
bazelbuild/bazel pull request #14383
Opened 2021-12-06 13:42 UTC by Yannic

Host transitions are problematic where the host and exec environment are
different (e.g., with Remote Execution). This change adds an incompatible
flag that fails analysis if Starlark rules use `cfg = "host"`.

Migrating is pretty straigt forward (replace `host` with `exec`) and
should be automatable by buildifier (although I haven't tried to do so).

2021-12-06 13:56 UTC, Yannic commented
@katre and/or @gregestren PTAL

2021-12-06 14:52 UTC, katre commented
@comius is actually working on something similar, so I'm assigning this to him so the two of you can discuss.

2021-12-15 08:07 UTC, comius commented
cc @susinmotion

I would attempt the more aggressive path first, where we just change all "host" transitions to "exec". This would reduce the churn substantially.

We're already fixing some issues that happen with that plan (within Bazel).

If this plan fails, this PR becomes viable alternative.

2021-12-21 23:01 UTC, Yannic commented
In my experiments, it seemed like tools build in exec config do get `--host_*` flags, so that plan doesn't look obviously broken (at least for local exec, didn't try remote exec yet but I should probably do that). SGTM

I think we should probably still make `cfg="host"` an error eventually even after `cfg="host" == cfg="exec"` (similar to what was done to `cfg="data"` which first became a no-op and was the removed), but we can handle that at a later point.

Should I send the documentation change in a separate PR? That seems useful regardless of whether we add the flag or not.

2022-02-01 21:04 UTC, gregestren commented
@susinmotion 's been focusing more on this recently. @susinmotion - do you have recommendations for @Yannic 's latest comment?

2022-02-01 21:26 UTC, susinmotion commented
Cool, thanks for thinking about this. A separate PR for documentation sounds great--we're really close to making this change.

I'm torn about making cfg="host" an error after the migration. On the one hand, it will make people's rules less confusing in the long term, since they'll say "exec" when they mean "exec". On the other hand, it causes breakages with things that aren't actually a problem, and that's a bummer for users. Can we do some kind of migration script here instead?

2022-02-21 19:06 UTC, Yannic commented
@susinmotion thanks for the update!

> Can we do some kind of migration script here instead?

Yes! Added a `buildifier` warning/fix for this: https://github.com/bazelbuild/buildtools/pull/1053

2022-03-23 06:51 UTC, comius commented
Hey, can you resolve the conflicts? Host transition has been removed now, so a flag to completely disable it is useful.

2022-04-06 06:28 UTC, comius requested changes
Please resolve the conflicts.

2022-04-11 05:44 UTC, comius commented
> Please resolve the conflicts.

Friendly ping.

2022-04-11 10:08 UTC, Yannic commented
@comius Updated, PTAL

2022-04-11 10:14 UTC, comius approved these changes

2022-04-11 14:00 UTC, comius commented on src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java
> +              + "'cfg = \"host\"' instead.")
Second host should be exec.

2022-04-11 15:02 UTC, Yannic commented on src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java
> +              + "'cfg = \"host\"' instead.")
```suggestion
              + "'cfg = \"exec\"' instead.")
```

2022-04-12 19:00 UTC, closed without merging

2022-04-12 19:01 UTC, brentleyjones commented
@bazel-io flag