Have README.md in java_tools release reference the right target
bazelbuild/bazel pull request #15093
Opened 2022-03-21 17:21 UTC by nresare

I was trying to figure out what produced the files included in https://github.com/bazelbuild/java_tools/releases/download/java_v11.6/java_tools-v11.6.zip that happens to have some instructions on how to re-produce the contents of the file. 

However, it turns out that the instructions in README.md references the wrong build target, which made it a bit confusing. This change updates the target to one that produces a zip that seem to contain the right files.

2022-03-23 06:10 UTC, comius requested changes

2022-03-23 06:10 UTC, comius commented on src/upload_java_tools.sh
> +$ bazel build //src:java_tools.zip
I think the same script is used for both prebuilt and non-prebuilt zips. This change would fix one but break 3 other platform. Please use `${platform}` variable here.

2022-03-29 14:40 UTC, comius commented
Friendly ping.

2022-04-04 06:02 UTC, comius commented
Second ping.

2022-04-04 08:23 UTC, nresare commented
Hi. I did spend some time on this, but unfortunately it seems with the latest macOS update bazel no longer compiles so I couldn't test it easily. I have now pushed an (untested) update to the script

2022-04-04 10:00 UTC, nresare commented
bumping the grpc dependency to it's latest released version fixed the compilation problem and I could test drive this. Now adding target platform as well when it is applicable.

In all cases where `java_upload_tools.sh` is used currently, it holds true that the output of `basename $java_tools_zip` is the same name as the target that is being packaged. It is a little magical, and might break in the future, but at least it is a lot better now than it was.

2022-04-06 06:28 UTC, comius approved these changes

2022-04-08 11:33 UTC, closed without merging