Add support for .ar archives (and .deb files)
bazelbuild/bazel pull request #15132
Opened 2022-03-28 15:46 UTC by kjlubick

This implements #[15130](https://github.com/bazelbuild/bazel/issues/15130).

As I was updating the docs for .ar and .deb formats, I also addressed some previous formats that had been added but not propagated through to all the documentation places.

2022-03-30 14:20 UTC, aiuto commented
I would like to find a way do to this without adding more code in Bazel. Perhaps we can do this mostly in starlark defined workspace rules.  I'm very familiar with the .deb and .ar formats on the writing side, so I'll take a look at this, but it might not be until next week.

2022-04-04 08:27 UTC, meteorcloudy commented
>  Perhaps we can do this mostly in starlark defined workspace rules.

How do you plan to do that? I think this PR extends the functionality of `repository_ctx.download_and_extract`, which is implemented in native code. Not sure how it could be implemented in pure starlark.

2022-04-04 11:37 UTC, kjlubick commented
I agree with @meteorcloudy, to implement this in pure starlark would involve decoding .ar files in Starlark code. This is not impossible, but certainly difficult given that we wouldn't really be able to use libraries. Another option is to shell out to a native executable, but that requires users to install or download such a binary.

2022-04-05 10:29 UTC, meteorcloudy requested changes

2022-04-05 10:29 UTC, meteorcloudy commented on src/main/java/com/google/devtools/build/lib/bazel/repository/ArFunction.java
> +                    Date lastModified = entry.getLastModifiedDate();
Getting this error message from internal presubmit check:
"Date has a bad API that leads to bugs; prefer java.time.Instant or LocalDate."

2022-04-05 10:29 UTC, meteorcloudy commented on src/main/java/com/google/devtools/build/lib/bazel/repository/ArFunction.java
> +import java.io.*;
Wildcard imports, static or otherwise, should not be used

2022-04-05 13:58 UTC, closed without merging

2022-04-11 15:50 UTC, ckolli5 commented
@bazel-io fork 5.2.0

2022-04-11 15:52 UTC, ckolli5 commented
@bazel-io fork 5.2.0

2022-04-21 09:53 UTC, uhthomas commented
Fixes https://github.com/bazelbuild/bazel/issues/13905?