SymlinkAction: Avoid using Artifact.prettyPrint in error messages.
bazelbuild/bazel pull request #15262
Opened 2022-04-14 19:48 UTC by benjaminp

As a comment in Artifact.prettyPrint notes: https://github.com/bazelbuild/bazel/blob/5d9333540a3ee9fe270e0e44eb4cc9fed8049bab/src/main/java/com/google/devtools/build/lib/actions/Artifact.java#L841-L842 prettyPrint can be confusing; in particular, it hides the artifact's root.

2022-04-19 14:31 UTC, haxorz approved these changes

2022-04-20 16:29 UTC, haxorz requested changes
Very sorry, @benjaminp! I wrote this comment yesterday but forgot to post it.

2022-04-20 23:11 UTC, benjaminp commented on src/test/shell/bazel/bazel_symlink_test.sh
> +  expect_log "failed to create symbolic link 'bazel-out/k8-fastbuild/bin/a/a.link': file 'a/foo.txt' is not executable"
Oops, I shoulda looked at the CI results.

I put a regular expression in the expectation now.

2022-04-21 00:17 UTC, haxorz approved these changes

2022-04-21 04:10 UTC, closed without merging