Add multiplex worker support to dexbuilder
bazelbuild/bazel pull request #15321
Opened 2022-04-22 19:46 UTC by Bencodes

Adding full support for multiplexed dexbuilder workers. This PR is a continuation of https://github.com/bazelbuild/bazel/pull/14623#issuecomment-1019852321 where we added basic worker support.

Related issue: https://github.com/bazelbuild/bazel/issues/10241

2022-05-03 19:15 UTC, nkoroste commented
Any updates on this?

2022-06-17 15:38 UTC, ted-xie commented
Oops, sorry for messing with the labels - I got some of my browser tabs mixed up. From a glance I don't see any major red flags; I'll discuss this internally.

2022-06-27 21:57 UTC, ted-xie requested changes
Overall looks good - would you mind adding a test for this flag in src/test/shell/bazel/android/android_integration_test.sh?

2022-06-27 22:04 UTC, ted-xie approved these changes
Actually, disregard my previous comment. I'll take care of the integration test. Overall LGTM, I'll push this through the internal processes.

2022-07-20 22:28 UTC, ahumesky commented
Rather than adding a separate flag, there's `--modify_execution_info`:

https://bazel.build/reference/command-line-reference#flag--modify_execution_info

So I think we could do the same thing with:

`--modify_execution_info=DexBuilder=+supports-multiplex-workers`

I believe that `--modify_execution_info` was added after `--use_workers_with_dexbuilder` was added, so that's why we have that hardcoded flag. We could actually remove `--use_workers_with_dexbuilder` as well and replace it with `--modify_execution_info`.

`--modify_execution_info` is admittedly a little clunkier than a specially purposed flag, but on the other hand, it might be better than proliferating several more flags.

2022-07-21 09:18 UTC, larsrc-google commented
Very much agree that we shouldn't add another tool-specific flag.

I'm starting to regret the `--experimental_worker_multiplex` flag being a boolean instead of a include/exclude list.

2022-07-22 17:04 UTC, Bencodes commented
What about instead of flag proliferation we introduce an `expansion` CLI flag that sets all of the necessary `--modify_execution_info` requirements for Android multiplex workers?

2022-07-22 17:43 UTC, Bencodes commented
The CLI expansion solution would look something like this. https://github.com/bazelbuild/bazel/pull/15950

2022-09-30 20:07 UTC, ahumesky commented
Thanks everyone, let's go with https://github.com/bazelbuild/bazel/pull/15950

2022-10-18 18:15 UTC, nkoroste commented
should we close this in favor of https://github.com/bazelbuild/bazel/pull/15950 to avoid confusion

2022-10-18 19:51 UTC, ahumesky commented
Yes that sounds good

2022-10-18 19:51 UTC, closed without merging