Add test cases for GenericTypeHelper class
bazelbuild/bazel pull request #15537
Opened 2022-05-20 05:51 UTC by rustberry

Hi there,

This commit adds test cases for uncovered/partially covered methods `isAssignableFrom` and `getActualReturnType` for `GenericTypeHelper` class in package `com.google.devtools.common.options`. Please feel free to request any changes needed.

2022-06-09 12:31 UTC, andyrinne12 requested changes
LGTM, just fix the typos.

2022-06-09 12:31 UTC, andyrinne12 commented on src/test/java/com/google/devtools/common/options/GenericTypeHelperTest.java
> +  public void assingableFromSuperSecondGrade() {
same typo

2022-06-11 05:58 UTC, rustberry commented
Hi Andrei, thank you very much for the careful review!

2022-06-14 11:07 UTC, andyrinne12 approved these changes
LGTM

2022-07-12 12:23 UTC, meteorcloudy commented
@sgowroji Can you please merge this?

2022-07-13 13:18 UTC, closed without merging