Deduplicate paths between old and new PYTHONPATH
bazelbuild/bazel pull request #15648
Opened 2022-06-09 15:34 UTC by ericsong

2022-06-09 16:22 UTC, ericsong commented
Not sure how to run rerun the `cla/google` check but I have since signed the CLA (with the correct email this time).

2022-06-09 20:40 UTC, ckolli5 commented
Hello @ericsong, I rerun the cla/google check and it is passed. Thanks!

2022-06-10 06:24 UTC, comius commented
I have a question. Is there a way to do this deduplication one level higher, that is when stub parameters are being substituted? Bazel has a lot of machinery to do this, and it might be nicer if the duplicates never get into the template.

2022-06-10 12:59 UTC, ericsong commented
I haven't tried it out yet but with that approach, we would be swapping it out [here](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPythonSemantics.java#L175) ?

I'm not sure if that would be possible since the duplicates are between that and the PYTHONPATH at runtime. We wouldn't know what [old_python_path](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L304) would be when the python script is being generated.

2022-06-15 12:41 UTC, ericsong commented
@comius thoughts on the above?

2022-06-20 07:00 UTC, comius requested changes

2022-06-20 07:00 UTC, comius commented on src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt
> +
Current implementation with joining, splitting, joining, is not the most readable.

Perhaps rewrite this block, by adding old_python_path to python_path_entries and then deduplicate and join with path separator.

2022-06-20 07:01 UTC, comius commented
> I haven't tried it out yet but with that approach, we would be swapping it out [here](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPythonSemantics.java#L175) ?
> 
> I'm not sure if that would be possible since the duplicates are between that and the PYTHONPATH at runtime. We wouldn't know what [old_python_path](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L304) would be when the python script is being generated.

Thanks @ericsong. Since it's coming from the environment, it in fact isn't possible to move it one layer higher.

2022-06-21 20:12 UTC, ericsong commented
thanks for the review @comius . I made some changes per your comment.

2022-07-21 10:49 UTC, comius approved these changes

2022-07-21 12:40 UTC, closed without merging