[credentialhelper] Add types to communicate with the subprocess
bazelbuild/bazel pull request #15803
Opened 2022-07-04 13:18 UTC by Yannic

This change adds `GetCredentials{Request,Response}`, which we'll use to
pass data in `stdin` to the credental helper subprocess, and read the
response from `stdout` of the subprocess.

Progress on https://github.com/bazelbuild/proposals/blob/main/designs/2022-06-07-bazel-credential-helpers.md#proposal

2022-07-04 13:19 UTC, Yannic commented
@tjgq PTAL

2022-07-05 10:17 UTC, tjgq requested changes

2022-07-05 10:17 UTC, tjgq commented on src/test/java/com/google/devtools/build/lib/authandtls/credentialhelper/GetCredentialsResponseTest.java
> +
Can you add tests for malformed `headers` fields, e.g.

`{"headers": null}`
`{"headers": "foo"}`
`{"headers": ["foo"]}`
`{"headers": {"foo": "bar"}}`

2022-07-07 15:40 UTC, tjgq approved these changes

2022-07-07 20:18 UTC, Yannic commented
@bazel-io flag

2022-07-08 08:42 UTC, closed without merging

2022-07-08 11:35 UTC, ckolli5 commented
@bazel-io fork 5.3.0