Use grpc 1.47.0
bazelbuild/bazel pull request #15822
Opened 2022-07-06 14:39 UTC by aranguyen

2022-07-13 14:51 UTC, meteorcloudy requested changes

2022-07-13 14:51 UTC, meteorcloudy commented on WORKSPACE
> +dist_http_archive(
You should move this before `load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")` to make sure our definitions can take precedence.

2022-07-13 14:55 UTC, meteorcloudy commented
To fix the src test, you'll have to define those `src` targets for com_github_cncf_udpa and com_envoyproxy_protoc_gen_validate:
https://github.com/bazelbuild/bazel/blob/4e54f6bea0d5daca0f0953a408559f510237bdc5/third_party/protobuf/BUILD#L9

2022-07-13 17:18 UTC, aranguyen reviewed
looks good. Thanks!

2022-07-14 09:00 UTC, meteorcloudy requested changes

2022-07-14 16:33 UTC, aranguyen commented
yikes...we're gonna need to pull in upd as well https://github.com/grpc/grpc/blob/2717aa8c9b768de99c811628af4e8c30d6c2da4f/bazel/grpc_deps.bzl#L349

2022-07-20 19:37 UTC, aranguyen commented
closing this to create a new one that is hopefully less messy and does not contain others' commits

2022-07-20 19:37 UTC, closed without merging