Add test coverage support to android_local_test
bazelbuild/bazel pull request #15840
Opened 2022-07-08 07:51 UTC by Bencodes

Adding test coverage support to android_local_test.

https://github.com/bazelbuild/bazel/issues/15827

2022-07-08 08:11 UTC, Tagakov approved these changes

2022-07-13 16:00 UTC, ted-xie requested changes

2022-07-14 20:15 UTC, ted-xie commented on src/test/shell/bazel/android/android_local_test_integration_test.sh
> +function assert_coverage_file_exists() {
It looks like there were some Windows-related failures in the latest presubmit; any idea about those?

2022-07-15 20:29 UTC, Bencodes commented on src/test/shell/bazel/android/android_local_test_integration_test.sh
> +function assert_coverage_file_exists() {
@ted-xie everything should be passing. The windows failures were build flakes.

2022-12-19 14:14 UTC, sofiethorsen commented
@ted-xie, @lberki, @ahumesky - are there any outstanding remarks you have on this PR that would block merging? I'm currently excluding all android tests when running coverage (only collecting coverage for pure Kotlin) - it would be beneficial to be able to include the android ones too.

2023-02-08 18:05 UTC, ted-xie commented
@sofiethorsen thanks for pinging me. I think we should merge this in.

2023-02-08 18:05 UTC, ted-xie approved these changes

2023-02-10 04:21 UTC, closed without merging

2023-02-28 20:28 UTC, keertk commented
@bazel-io fork 6.1.0