[credentialhelper] Implement invoking credential helper as subprocess
bazelbuild/bazel pull request #15861
Opened 2022-07-11 20:26 UTC by Yannic

Progress on https://github.com/bazelbuild/proposals/blob/main/designs/2022-06-07-bazel-credential-helpers.md

2022-07-11 20:46 UTC, Yannic commented
@tjgq PTAL

2022-07-12 09:02 UTC, tjgq requested changes

2022-07-14 13:26 UTC, Yannic commented on src/main/java/com/google/devtools/build/lib/authandtls/credentialhelper/CredentialHelper.java
> +      process.waitFor();
We should!

2022-07-14 13:29 UTC, Yannic commented on src/test/java/com/google/devtools/build/lib/authandtls/credentialhelper/test_credential_helper.py
> +    if argv[1] == "get":
done

2022-07-14 13:45 UTC, Yannic commented on src/main/java/com/google/devtools/build/lib/authandtls/credentialhelper/CredentialHelper.java
> +                "Failed to get credentials from helper (exited with code %d): %s",
done

2022-07-14 14:07 UTC, Yannic commented
PTAL

2022-07-14 14:33 UTC, tjgq approved these changes

2022-07-14 15:14 UTC, tjgq commented on src/main/java/com/google/devtools/build/lib/authandtls/credentialhelper/CredentialHelper.java
> +      process.waitFor();
FYI, I will change the timeout error message before submitting internally, because `Duration#toString` doesn't produce a human-readable format.

2022-07-15 09:54 UTC, closed without merging

2022-07-15 17:06 UTC, Yannic commented
@bazel-io flag

2024-11-29 08:17 UTC, Allenqel commented
credential helper] Implement invoking credential helper as subprocess(15861)