Throw explicit exception if experimental_split_coverage_postprocessing is used without experimental_fetch_all_coverage_outputs
bazelbuild/bazel pull request #16140
Opened 2022-08-21 10:23 UTC by blindpirate

This closes https://github.com/bazelbuild/bazel/issues/13185
According to https://github.com/bazelbuild/bazel/commit/e411fa74176cdc54f84d62c189d042e9fb6d5c79,
The flag --experimental_split_coverage_postprocessing depends on the flag
--experimental_fetch_all_coverage_outputs being enabled, but if the former one
is set without the latter one, Bazel throws a quite confusing NullPointerException.
Now we throw an explicit exception with proper error message.

2022-09-01 06:38 UTC, blindpirate commented
@sgowroji The failure seems to be because CI machine is disconnected from Internet, can you give me some hints how to handle external dependencies which need to be downloaded in integration tests?

2022-09-16 12:26 UTC, oquenchil approved these changes
LGTM

2022-09-27 12:24 UTC, oquenchil commented
Adding @c-mita

2022-10-04 09:45 UTC, c-mita requested changes
The test setup can be greatly simplified; it should be unnecessary to pull in the `rules_cc` stuff.

2022-10-04 09:45 UTC, c-mita commented on src/test/shell/bazel/bazel_coverage_cc_test_gcc.sh
> +  EXPECT_EQ(get_greet("Bazel"), "Hello Bazel");
This could just be `return 0;` or something - the actual test result doesn't matter, and we don't want to try pulling in gtest.

2022-10-04 09:45 UTC, c-mita commented on src/main/java/com/google/devtools/build/lib/exec/StandaloneTestStrategy.java
>        String errorMessage = "cannot run local tests with --nobuild_runfile_manifests";
Can remove this now unused local variable.

2022-10-04 09:45 UTC, c-mita commented on src/test/shell/bazel/bazel_coverage_cc_test_gcc.sh
> +EOF
If you actually want a file under test, there's no need to make it complicated; a simple `int foo() { return 42; }` is more than sufficient here; we really don't care about the coverage reports, only that the flag combination raises an error,

2022-10-05 03:52 UTC, blindpirate commented
Hi @sgowroji @oquenchil @c-mita now it's all green, PTAL!

2022-10-06 07:26 UTC, closed without merging

2022-10-06 07:34 UTC, sgowroji commented
Thank you @blindpirate !