errors: noBuildFile suggests BUILD.bazel too
bazelbuild/bazel pull request #16207
Opened 2022-09-02 12:50 UTC by iamricard

Hi 👋🏼 apologies for the unsolicited submission, this just seemed like a simple QOL improvement for bazel errors so I figured I'd give it a shot (not sure how much of this code is shared with blaze if any at all so I understand if this can't make it in because of google3).

Because there are three kinds of files bazel really cares about (BUILD, BUILD.bazel, and *.bzl) for people unfamiliar with the system it can be confusing that BUILD.bzl, for example, wouldn't work (we've seen this happen). If the noBuildFile error message suggests either BUILD or BUILD.bazel, it becomes more obvious that those are the only two options.

2022-09-26 15:48 UTC, iamricard commented
ping @sgowroji 👀 wondering if this could get accepted or if i should just close it (so that it doesn't keep showing up on my open PRs)

2022-09-26 15:53 UTC, sgowroji commented
@iamricard  Thank you for the patience. We have shared the PR  to our internal team. You will be seeing the significant update very soon.

2022-09-26 16:28 UTC, Wyverald approved these changes

2022-11-02 19:25 UTC, brandjon requested changes
Not sure why this wasn't merged yet, but looking at it now I have a comment:

We have tons of places where we refer to "BUILD files" -- in code, in error strings, and in user documentation. Should we update virtually all of them to say "BUILD or BUILD.bazel"? I think we'd all agree that's probably overkill, but then what makes it more worthwhile for just this one error message? And what policy should we follow for other occurrences?

(If BUILD.bzl is a common mistake, I'd be tempted to check for the presence of that file and emit a special error in that case. But that's probably too complicated to do in Skyframe, given how many hoops we jump through to lookup where BUILD files are. And it'd need tests for interaction with `--package_path`, etc., to the point that it couldn't be worthwhile.)

2022-12-19 17:29 UTC, brandjon commented
I'm going to close this for lack of certainty as to how to address this problem in general for all error messages / documentation. Filed #17054 to track.

2022-12-19 17:29 UTC, closed without merging