[remote/downloader] Add incompatible flag for sending a list of headers as qualifier
bazelbuild/bazel pull request #16312
Opened 2022-09-20 20:46 UTC by Yannic

2022-09-20 20:47 UTC, Yannic commented
@tjgq PTAL

Ideally, I'd like to flip this before Bazel 6.0.0 to limit who depends on it. Not sure how feasible that is though.

2022-09-22 17:45 UTC, tjgq commented
> @tjgq PTAL
> 
> Ideally, I'd like to flip this before Bazel 6.0.0 to limit who depends on the old behavior. Not sure how feasible that is though.

AIUI the 6.0.0 branch cut has been postponed to Oct 10 (https://github.com/bazelbuild/bazel/issues/16159#issue-1349197485), so we still have some time. I agree that we should flip it; the sooner the better, so that our nightly downstream pipeline can catch anything that breaks.

2022-09-28 10:31 UTC, tjgq requested changes

2022-09-28 11:44 UTC, Yannic commented on src/main/java/com/google/devtools/build/lib/remote/options/RemoteOptions.java
> +          name = "incompatible_remote_downloader_send_all_headers",
No. This flag is specific to `GrpcRemoteDownloader` and the remote assets API for downloading.

2022-09-28 11:47 UTC, Yannic commented on src/main/java/com/google/devtools/build/lib/remote/options/RemoteOptions.java
> +          help = "Whether to sens all headers to the remote downloader instead of just the first.")
```suggestion
          help = "Whether to send all values of a multi-valued header to the remote downloader instead of just the first.")
```

2022-09-28 11:48 UTC, Yannic reviewed
PTAL

2022-09-29 16:26 UTC, tjgq approved these changes

2022-09-29 18:09 UTC, closed without merging