Upload all logs in BEP even with minimal upload
bazelbuild/bazel pull request #17110
Opened 2023-01-02 14:32 UTC by exoson

When using --experimental_remote_build_event_upload=minimal, build action logs won't get uploaded. These logs are still very useful as when a build action fails, one would need to inspect them to figure out what has gone wrong. Forcing uploading stdout and stderr with this change.

2023-01-04 15:37 UTC, coeuvre requested changes
Do we always want to upload action logs or only upload when they failed?

Please add a test case for this similar to [test_upload_minimal_upload_testlogs](https://cs.opensource.google/bazel/bazel/+/master:src/test/shell/bazel/remote/remote_build_event_uploader_test.sh;l=245;drc=6b5277294bfcf032d1d2d009c102147af12ec896).

2023-01-05 06:51 UTC, exoson commented
Seems that at least currently the build event file won't reference the build logs unless the action had failed so the logs will only be uploaded for failing actions.

2023-01-05 14:03 UTC, brentleyjones commented
@bazel-io flag

2023-01-09 16:47 UTC, closed without merging

2023-01-19 19:18 UTC, kshyanashree commented
@bazel-io fork 6.1.0