Fix deps target
bazelbuild/bazel pull request #17199
Opened 2023-01-12 12:31 UTC by vbhavsar

Fixes #17198

2023-02-16 17:42 UTC, vbhavsar commented
CLA check now passes. Can the checks be re-triggered?

2023-02-22 08:47 UTC, sgowroji commented
Hi @vbhavsar, I triggered the checks couple of times but still the buildkite checks are failling. Could you please have a look and fix the above errors, So that we can share it for further review. Thanks!

2023-11-13 18:44 UTC, rickeylev requested changes

2023-11-13 18:44 UTC, rickeylev commented on src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPyBinaryRule.java
> +    deps = [":testing"],
The example seems to be showing a java_library wanting to use a py_binary. If you look below, the java_library has this py_binary in data.

I dunno what this deps line is for. There doesn't appear to be any definition of the "testlib" target. So lets just remove it entirely.

```suggestion
```

2025-02-01 20:18 UTC, vbhavsar commented
Not sure why this isn't being reviewed. Closing.

2025-02-01 20:18 UTC, closed without merging