Add multiplex worker assertions for desugaring
bazelbuild/bazel pull request #17351
Opened 2023-01-27 20:42 UTC by Bencodes

2023-04-04 04:09 UTC, Bencodes commented
Opened up a cherry pick here for when this lands in master https://github.com/bazelbuild/bazel/pull/17965

2023-04-04 19:45 UTC, ted-xie requested changes

2023-04-04 21:35 UTC, Bencodes commented on src/main/java/com/google/devtools/build/lib/rules/android/AndroidConfiguration.java
> -        name = "use_workers_with_dexbuilder",
Updated

2023-04-06 18:22 UTC, ted-xie approved these changes
Overall LGTM, there is just one more thing to fix (that we can handle internally) - we'll have to move the deprecated @Option stanza from BazelBuildGraveyardOptions class to the BuildGraveyardOptions class.

2023-04-12 14:42 UTC, closed without merging

2023-04-19 21:23 UTC, keertk commented
@bazel-io fork 6.2.0