Adding log sort flag to disable stable sort and get better memory performance in some situations
bazelbuild/bazel pull request #17354
Opened 2023-01-29 14:55 UTC by YuanHao97

fix #17111 
add log sorting flag to disable stable sort and get better memory performance in some situations.
command line flag: --execution_log_sort
possible values: 
true : use stable sort as before when writing logs to a file. See com.google.devtools.build.lib.bazel.execlog.StableSort#stableSort
false : do not sort logs. Write directly from input stream to output stream.

2023-01-31 14:25 UTC, tjgq requested changes

2023-01-31 14:25 UTC, tjgq commented on .gitignore
> +.bazeliskrc
Please remove (I'm not sure what our stance is on adding additional entries to .gitignore, but if you really want to add it, this is better discussed in a separate PR.)

2023-01-31 14:25 UTC, tjgq commented on src/main/java/com/google/devtools/build/lib/bazel/SpawnLogModule.java
> +            StableSort.ignoreSort(in, outputStreams);
It's a little odd to have a method on `StableSort` that doesn't sort at all. Can you just inline `ignoreSort` here?

2023-01-31 14:25 UTC, tjgq commented on src/main/java/com/google/devtools/build/lib/exec/SpawnLogContext.java
> +  public boolean needSort() {
Nit: `shouldSort` is more in line with how we call this kind of method elsewhere in the codebase.

2023-01-31 14:25 UTC, tjgq commented on src/main/java/com/google/devtools/build/lib/exec/ExecutionOptions.java
> +              + " a stable order or not, can be disabled to optimize memory performance.")
```suggestion
          "Whether to sort the execution log. Set to false to improve memory"
              + " performance, at the cost of producing the log in nondeterministic"
              + " order.")
```

2023-01-31 14:25 UTC, tjgq commented on src/main/java/com/google/devtools/build/lib/exec/ExecutionOptions.java
> +              + " a stable order or not, can be disabled to optimize memory performance.")
Just to confirm my understanding here: the flag affects both the delimited proto and JSON versions of the execution log, right?

2023-02-07 13:25 UTC, YuanHao97 commented
@tjgq Hi, I've updated some files and got 5 failed tests. How can I resolve those failed checks? Thanks!

2023-02-08 10:46 UTC, tjgq commented on src/main/java/com/google/devtools/build/lib/bazel/SpawnLogModule.java
> +            StableSort.ignoreSort(in, outputStreams);
To clarify, what I meant was to move the `if (shouldSort) { stableSort(...) } else { ... }` logic into the `SpawnLogModule` class, and leave only the `stableSort` method in the `StableSort` class.

2023-02-09 01:36 UTC, YuanHao97 commented
@tjgq Sorry,  I got some compiling problems before push, so it's difficult to do verification.
BTW, I'm using Intellij IDEA and seems some packages are not found:
`import com.google.common.collect.ImmutableList;`
`import com.google.devtools.build.lib.exec.Protos.SpawnExec;`
I'm not sure why `com.google.common.collect.ImmutableList` is not found. Is there any more dependencies I should add?
I guess `com.google.devtools.build.lib.exec.Protos.SpawnExec` should be generated by some protobuf plugins, at least for maven project. But how to do that in Bazel project?

2023-02-10 11:13 UTC, tjgq commented
> @tjgq Sorry, I got some compiling problems before push, so it's difficult to do verification. BTW, I'm using Intellij IDEA and seems some packages are not found: `import com.google.common.collect.ImmutableList;` `import com.google.devtools.build.lib.exec.Protos.SpawnExec;` I'm not sure why `com.google.common.collect.ImmutableList` is not found. Is there any more dependencies I should add? I guess `com.google.devtools.build.lib.exec.Protos.SpawnExec` should be generated by some protobuf plugins, at least for maven project. But how to do that in Bazel project?

To get Intellij support for Bazel builds, see https://ij.bazel.build/.

I think this looks good now. Could you please sign the CLA (https://github.com/bazelbuild/bazel/pull/17354#issuecomment-1407685117) so I can start the import process?

2023-02-11 04:55 UTC, YuanHao97 commented
@tjgq I've already siged cla. Please take a look at the check list.

2023-02-15 14:20 UTC, tjgq commented
> @tjgq I've already siged cla. Please take a look at the check list.

My bad, sorry. I'll start the import process.

2023-02-15 15:06 UTC, closed without merging

2023-02-15 15:07 UTC, brentleyjones commented
@bazel-io flag

2023-02-15 19:06 UTC, kshyanashree commented
@bazel-io fork 6.1.0