Change tar file format for
bazelbuild/bazel pull request #17679
Opened 2023-03-07 15:29 UTC by ahryniv

In Python 3.8. [default format](https://docs.python.org/3/library/tarfile.html#tarfile.DEFAULT_FORMAT) of tarfiles was changed to `PAX_FORMAT`.

`dpkg` rejects tarfiles with PAX format with an "unsupported PAX tar header type" message.

Setting the tarfile format explicitly to `GNU_FORMAT`(default before Python 3.8 version) when creating tarfiles fixes the problem.

see related:
* https://github.com/bazelbuild/rules_pkg/pull/217
* https://github.com/bazelbuild/rules_pkg/pull/601

2023-03-07 18:55 UTC, cwoerner commented on tools/build_defs/pkg/archive.py
> +    self.tar = tarfile.open(name=name, mode=mode, fileobj=self.fileobj, format=tarfile.GNU_FORMAT)
Rather than hacking archive.py, can pkg.archive.tar be monkey patched at runtime from within our code?

2023-03-07 18:58 UTC, cwoerner commented on tools/build_defs/pkg/archive.py
> +    self.tar = tarfile.open(name=name, mode=mode, fileobj=self.fileobj, format=tarfile.GNU_FORMAT)
Oh, I see, it's a context manager object, so likely no.   Huh, ok, let's discuss more.

2023-03-07 19:06 UTC, cwoerner requested changes

2023-03-07 19:06 UTC, cwoerner commented on tools/build_defs/pkg/archive.py
> +    self.tar = tarfile.open(name=name, mode=mode, fileobj=self.fileobj, format=tarfile.GNU_FORMAT)
If you hope to push this upstream you shouldn't set format=tarfile.GNU_FORMAT in the tarfile.open method invocation, but rather define an additional named argument  to the TarFileWriter constructor called "format" with a default value (e.g format=tarfile.DEFAULT), then pass that into the tarfile.open() function.

2023-03-07 19:23 UTC, cwoerner commented on tools/build_defs/pkg/archive.py
> +    self.tar = tarfile.open(name=name, mode=mode, fileobj=self.fileobj, format=tarfile.GNU_FORMAT)
Also, add tests to archive_test.py for the parameter change I suggested above.

2023-03-28 13:38 UTC, aiuto reviewed
We will not take this patch.  The internal pkg_tar is deprecated and slowly being removed. Users must migrate to https://github.com/bazelbuild/rules_pkg.

2023-03-28 13:38 UTC, closed without merging