Rework ByteStreamUploader early return logic.
bazelbuild/bazel pull request #17791
Opened 2023-03-15 21:18 UTC by benjaminp

There are several points where ByteStreamUploader may discover that the server already has the blob fully uploaded. These points tried to effect an early return from the upload code, generally by "lying" to higher layers that the upload fully finished. That could lead to bugs. For example, consider the added test case: A compressed upload completes its writing but receives an error instead of a server ACK. On retry, QueryWriteStatus reveals the blob exists and returns its uncompressed size. This confused the checkCommittedSize logic, which expected the final committed size of a compressed upload to be the total compressed data size or -1. The code added by https://github.com/bazelbuild/bazel/commit/daa3dbe22adb03338c75b53ea97954c9434099b4 also looks broken in the case of compressed uploads.

Rework the uploader code, so that early returns throw a AlreadyExists exception. The exception control flow naturally reflects the desire to escape quickly to the top level.

2023-03-16 04:19 UTC, benjaminp commented
This change revealed preëxisting defects in `Chunker`. The tests pass with #17797 applied.

2023-03-16 09:50 UTC, coeuvre requested changes
LGTM. Please rebase after #17797 is merged.

2023-03-16 15:37 UTC, coeuvre approved these changes

2023-03-17 04:06 UTC, sgowroji commented
Hi @coeuvre, Since I can see that this PR has been approved, please let me know whether I should proceed with importing it.

2023-03-17 10:06 UTC, coeuvre commented
Argh, sorry, I forgot to add the right label. Please import it, thanks!

2023-03-17 12:33 UTC, closed without merging

2023-03-17 18:14 UTC, Yannic commented
@bazelio flag

2023-03-17 18:14 UTC, Yannic commented
@bazel-io flag

2023-03-17 21:12 UTC, keertk commented
@bazel-io fork 6.2.0