Add jsonproto option to query --output flag
bazelbuild/bazel pull request #18187
Opened 2023-04-24 00:52 UTC by chiragramani

Addresses https://github.com/bazelbuild/bazel/issues/17627

2023-05-04 09:20 UTC, zhengwei143 requested changes
Thanks for the PR! Could you also add this format to the option's help description (https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/query2/query/output/QueryOptions.java#L42-L43)?

2023-05-09 08:38 UTC, zhengwei143 approved these changes

2023-05-10 10:16 UTC, closed without merging

2023-05-16 21:55 UTC, chiragramani commented
@bazel-io flag

2023-05-17 16:31 UTC, iancha1992 commented
@bazel-io fork 6.3.0