Use failure_rate instead of failure count for circuit breaker
bazelbuild/bazel pull request #18539
Opened 2023-05-30 21:46 UTC by amishra-u

Continuation of #18359
I ran multiple experiment and tried to find optimal failure threshold and failure window interval with different remote_timeout, for healthy remote cache, semi-healthy (overloaded) remote cache and unhealthy remote cache. 
As I described [here](https://github.com/bazelbuild/bazel/pull/18359#issuecomment-1542589266) even with healthy remote cache there was 5-10% circuit trip and we were not getting the best result. 

Issue related to the failure count:
1. When the remote cache is healthy, builds are fast, and Bazel makes a high number of calls to the buildfarm. As a result, even with a moderate failure rate, the failure count may exceed the threshold.
2. Additionally, write calls, which have a higher probability of failure compared to other calls, are batched immediately after the completion of an action's build. This further increases the chances of breaching the failure threshold within the defined window interval.
3. On the other hand, when the remote cache is unhealthy or semi-healthy, builds are significantly slowed down, and Bazel makes fewer calls to the remote cache.

Finding a configuration that works well for both healthy and unhealthy remote caches was not feasible. Therefore, changed the  approach to use the failure rate, and easily found a configuration  that worked effectively in both scenarios.

2023-05-30 23:04 UTC, linzhp commented
@coeuvre Can you review?

2023-05-31 09:05 UTC, coeuvre requested changes

2023-05-31 09:05 UTC, coeuvre commented on src/main/java/com/google/devtools/build/lib/remote/circuitbreaker/FailureCircuitBreaker.java
> +      double failureRate = (failureCount * 100.0) / totalCallCount;
Please document in the `help` that the unit of rate is in percentage instead of normalized.

2023-05-31 16:03 UTC, coeuvre approved these changes

2023-06-07 21:13 UTC, closed without merging