Add the remote_require_cached flag
bazelbuild/bazel pull request #18942
Opened 2023-07-14 16:07 UTC by jmmv

When set to true, this flag causes Bazel to abort the build whenever it encounters an action that is not cached.

This is very useful when trying to troubleshoot action non-determinism issues because it allows running a build and having it fail as soon as there is a problem without tainting what already exists in the cache.

My workflow is to essentially do:

1. bazel build ...
2. bazel clean
3. bazel build --remote_require_cached ...

which makes step 3 fail on the first non-deterministic action. Then I can address that problem and re-run step 3 to encounter the next issue.

2023-07-17 09:45 UTC, coeuvre requested changes

2023-07-17 09:45 UTC, coeuvre commented on src/main/java/com/google/devtools/build/lib/remote/options/RemoteOptions.java
> +      name = "remote_require_cached",
Can we add a `experimental_` prefix?

2023-07-17 14:01 UTC, jmmv commented on src/main/java/com/google/devtools/build/lib/remote/options/RemoteOptions.java
> +      name = "remote_require_cached",
Done.

2023-07-17 20:54 UTC, jmmv commented
I've updated the description of the PR as well as the one in the commit (which required a force-push) to more clearly explain how this flag is useful. I don't think the original thing I wrote made a lot of sense.

2023-07-18 09:00 UTC, coeuvre approved these changes
Thanks!

2023-07-19 08:49 UTC, closed without merging

2023-07-25 02:48 UTC, brentleyjones commented
@bazel-io flag

2023-09-21 20:51 UTC, iancha1992 commented
The changes in this PR have been included in [Bazel 6.4.0 RC1](https://releases.bazel.build/6.4.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.
Thanks!