TMP: Flip `--incompatible_visibility_private_attributes_at_definition`
bazelbuild/bazel pull request #19141
Opened 2023-08-01 10:09 UTC by fmeum

2023-08-01 10:49 UTC, fmeum commented
@meteorcloudy I would like to see this flag flipped, but would like to see the results of a downstream run before I bring this up for discussion. Could you trigger one for me on this PR?

2023-08-01 11:09 UTC, meteorcloudy commented
Here you go: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds?branch=pull%2F19141%2Fhead 

But there are many existing failures in downstream pipeline, you may need to compare the results.

2023-08-25 10:45 UTC, fmeum commented
Not entirely sure which team this belongs to, but based on prior interactions about this flag and the relation to visibility, I will go with `Team-Configurability`.

@aranguyen Could you review this? I had a previous discussion about this with Greg on https://github.com/bazelbuild/bazel/pull/19139. We can also wait for Greg to be back in office if you don't feel like you have sufficient context.

CC @laurentlb as the reviewer of the original proposal (https://github.com/bazelbuild/proposals/blob/main/designs/2019-10-15-tool-visibility.md). With load visibility available now, there doesn't seem to be any reason not to flip this *for Bazel*. Blaze may be a different story, but could be solved with an RC file entry if you don't want to perform a migration.

2023-09-06 12:49 UTC, comius approved these changes
This has a potential to show preexisting correctness bugs on unexpected edge cases. I'll run the internal tests and report back.

2023-09-06 12:55 UTC, comius commented
@brandjon, can you provide a second pair of eyes? 

This has been implemented in 2019: PiperOrigin-RevId: 277683498

Technically this could show us some edge cases / correctness issues. I remember fixing one related to this in the past that involved about 5 conditions to trigger.

I'll run internal tests and if we don't have a plan for other actions that could de-risk us, I propose we move forward.

This is a feature that both internal and external users were asking for and is a pain point for toolchain owners in general.

@fmeum I don't see aspects covered in the tests of the original implementation. Could you add some tests for that? Should an implicit dependency in that case be visible to an aspect, not rule?

cc @mai93

2023-09-06 13:01 UTC, comius requested changes
Please add tests that cover aspect's implicit dependecies and implicit dependencies of targets an aspect is over.

2023-09-06 14:14 UTC, comius commented
I believe IntelliJ issues are related to aspects functionality. Please address them.

2023-09-22 07:26 UTC, fmeum commented
@comius I made the change you suggested in https://github.com/bazelbuild/bazel/issues/19330#issuecomment-1729030797.

2023-09-22 17:27 UTC, mai93 commented on src/test/java/com/google/devtools/build/lib/analysis/VisibilityTest.java
> +    assertThat(hasErrors(getConfiguredTarget("//use:world"))).isFalse();
Can we update the name of this test to show the fall back to the target?

2023-09-29 19:19 UTC, closed without merging

2023-10-27 08:22 UTC, comius commented
There's one use case we haven't foreseen. Restricting visibility of tools to **builtin rules**.

2023-10-27 08:29 UTC, fmeum commented
@comius Could you elaborate on this? Wouldn't something like `visibility = ["@_builtins//..."]` work?

2023-10-27 12:33 UTC, comius commented
> @comius Could you elaborate on this? Wouldn't something like `visibility = ["@_builtins//..."]` work?

I've just got a report from an internal user, that they tried `"@_builtins//:__pkg__"` and that it doesn't work. The error message indicates that fallback happened, however I didn't try it.

It happened on an internal ruleset. Possibly a simple reproduction in Bazel is to reduce visibility of @bazel_tools/tools/def_parser:def_parser, which is used in cc_binary

2023-10-29 10:52 UTC, fmeum commented
I checked that `visibility = ["@@_builtins//:__subpackages__"]` on `def_parser` suffices to build `cc_binary`s. Note the double `@`, which is necessary since `_builtins` does not have a repo mapping entry in `bazel_tools`.

@comius If a rule `foo` extends a rule `bar`, are implicit dependencies of `bar` checked against the definition of `bar` (instead of `foo`)? I could see this leading to problems if not.

2023-10-30 14:28 UTC, Wyverald commented
cc also @brandjon; this is somewhat annoying since `@_builtins` is really a "pseudo-repo" -- it doesn't have a definition, you can't build any targets in it, and the only thing you're really allowed to do is to `load` .bzl files from it. I'm not too familiar with what this PR entails, but if it has now required `@_builtins` to be an actual repo, we might need to have a more principled solution.