Ignore read-only errors when updating the `mtime` of the `install_base`
bazelbuild/bazel pull request #20442
Opened 2023-12-05 20:50 UTC by rrbutani

> [!NOTE]
> Follow-up to #20373 (see [here](https://github.com/bazelbuild/bazel/pull/20373#issuecomment-1833512588))

---

Currently if the `--install_base` path passed is not writable by the user invoking Bazel, the Bazel client crashes:
```console
❯ bazel --install_base=/some/read/only/path version
FATAL: failed to set timestamp on '/some/read/only/path': (error: 30): Read-only file system
```

This happens because the Bazel client (unconditionally) attempts to update the `mtime` of this path:
https://github.com/bazelbuild/bazel/blob/a3c677dfea2de636a719d50345a5a97af96fae60/src/main/cpp/blaze.cc#L1010-L1021

This commit updates the client to ignore such errors. See #20373 for context.

---

cc: @tjgq

2023-12-05 20:52 UTC, rrbutani commented on src/main/cpp/blaze.cc
> +#if defined(__linux__) || defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__APPLE__) || defined(__CYGWIN__)
Wasn't sure whether listing out these POSIX-y platforms explicitly was required (or if just using `!defined(_WIN32)` would be sufficient).

2023-12-05 20:52 UTC, rrbutani commented on src/main/cpp/blaze.cc
> +      if (::GetLastError() == ERROR_ACCESS_DENIED) { raise_error = false; }
I am not sure whether this is correct; unfortunately I don't have access to a Windows machine at the moment.

2023-12-09 19:30 UTC, tjgq requested changes
We try to keep the platform-dependent filesystem code in `file_platform.h` and its two implementations, `file_posix.cc` and `file_windows.cc`.

How about adding a new `SetToNowIfPossible` method there with the desired "permissions error counts as success" semantics?

2023-12-14 17:08 UTC, tjgq approved these changes

2023-12-15 16:47 UTC, closed without merging

2023-12-15 16:55 UTC, brentleyjones commented
@bazel-io flag

2023-12-15 17:58 UTC, iancha1992 commented
@bazel-io fork 7.1.0

2023-12-15 17:59 UTC, iancha1992 commented
@brentleyjones please let me know if you want this included with 6.5.0 as well.

2023-12-15 18:54 UTC, brentleyjones commented
@iancha1992 If it applies nicely, it would be good to get in, yes.

2023-12-15 19:15 UTC, iancha1992 commented
@bazel-io fork 6.5.0

2024-01-17 00:26 UTC, iancha1992 commented
The changes in this PR have been included in [Bazel 6.5.0 RC1](https://releases.bazel.build/6.5.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.
Thanks!

2024-02-23 00:16 UTC, iancha1992 commented
The changes in this PR have been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.
Thanks!