Update index.md to let the users know that they can create a cherry-pick request on their own
bazelbuild/bazel pull request #20865
Opened 2024-01-12 06:22 UTC by iancha1992

2024-01-12 06:23 UTC, iancha1992 commented
cc: @keertk

2024-01-12 11:29 UTC, meteorcloudy requested changes

2024-01-12 11:29 UTC, meteorcloudy commented on site/en/release/index.md
> +    *   A user may also choose to cherry-pick certain commit(s) on their own by creating a [cherry-pick request](https://github.com/bazelbuild/bazel/issues/new?assignees=&labels=&projects=&template=c
"A user may also choose to cherry-pick certain commits" is not accurate. First, not all requests will be accepted, it depends on the author and reviewer of the commits. Also, a public user cannot add milestone to the issue, so this is limited to Bazel maintainers to use this issue.

2024-01-17 09:41 UTC, meteorcloudy approved these changes
Awesome, thanks!

2024-01-19 09:00 UTC, closed without merging