Add `target_kind` to scrubber matching rules
bazelbuild/bazel pull request #21151
Opened 2024-01-31 10:47 UTC by bozaro

Allow the use of the target kind (for example, `cc_library`, `go_binary`, `go_test`...) in the scrubbing matcher configuration.
This is useful, as different target kinds can have the same mnemonic.

2024-02-01 11:12 UTC, tjgq requested changes
Looks good to me, but please add tests in `//src/test/java/com/google/devtools/build/lib/remote/ScrubberTest.java`. You can use the test cases for `label_regex` (i.e., `matchExactLabel`, `matchUnionLabel` and `matchWildcardLabel`) as a starting point.

2024-02-01 11:12 UTC, tjgq commented on src/main/protobuf/remote_scrubbing.proto
> +    // A regex matching the action target kind.
"A regex matching the rule kind of the action owner."

2024-02-09 13:27 UTC, tjgq approved these changes

2024-02-09 13:27 UTC, tjgq commented
I don't believe the CI failures are related. Importing.

2024-02-09 13:28 UTC, tjgq commented
@bazel-io fork 7.1.0

2024-02-09 15:34 UTC, closed without merging

2024-02-09 16:20 UTC, tjgq commented
FYI - I renamed the `target_kind` config property to just `kind`, but otherwise the submitted code matches your PR.

2024-02-22 22:46 UTC, iancha1992 commented
The changes in this PR have been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.
Thanks!