[7.1.0] Mark gcc-<version> as `gcc` instead of `compiler` in Unix CC toolchain
bazelbuild/bazel pull request #21224
Opened 2024-02-06 20:06 UTC by iancha1992

Fixes #17794

I was looking at writing a test for this, but not sure how you'd like me to go about that. Hard-code a gcc, e.g. `gcc-11`, or search the `$PATH` for a `gcc-<version>`?
    
Closes #20350.

Commit https://github.com/bazelbuild/bazel/commit/88771830d92a93027ed7dfb5d130b3311400dbc4
    
PiperOrigin-RevId: 604543138
Change-Id: I71ebbac77e4e32ebc5d99ec4a81415727af12cbc

2024-02-06 21:44 UTC, iancha1992 commented
@comius @Wyverald any idea why there's an error to update the lockfiles? I've already ran the `bazel run //src/test/tools/bzlmod:update_default_lock_file` and `bazel mod deps --lockfile_mode=update`

cc: @bazelbuild/triage

2024-02-07 11:36 UTC, comius approved these changes

2024-02-07 16:15 UTC, meteorcloudy requested changes

2024-02-07 16:15 UTC, meteorcloudy commented on MODULE.bazel.lock
> +        "bzlTransitiveDigest": "c5rSaV6x0pI1k3yDrGa+nTeCN9zzlhd11tP9VzHzc+o=",
This should not be changed.

2024-02-08 09:42 UTC, meteorcloudy approved these changes

2024-02-08 18:03 UTC, merged