refactor: allow relative symlinks that points out of the treeartifact
bazelbuild/bazel pull request #21263
Opened 2024-02-08 19:49 UTC by thesayyn

Fixes https://github.com/bazelbuild/bazel/issues/20891

2024-02-08 19:49 UTC, thesayyn commented
cc @tjgq @comius

2024-02-09 07:09 UTC, comius commented
> cc @tjgq @comius

Thanks. I believe @tjgq is more qualified reviewer in this case.

2024-02-09 12:33 UTC, tjgq requested changes
LGTM generally, but let's leave some tests in place to catch regressions.

2024-02-14 12:18 UTC, tjgq commented
df07d275ce17f14224af0f1a5862755a7db44397 touched some code around this area, so you'll have to rebase your PR.

2024-02-14 18:02 UTC, thesayyn commented
All right. I'll get to it soon hopefully.

2024-02-20 05:32 UTC, thesayyn commented
@tjgq dangling symlinks isn't seem to be supported anymore. is that expected?  i get tests failing with "is a dangling symbolic link"

2024-02-20 05:42 UTC, thesayyn commented
Also would it be possible to cherry pick this into 7.1.0? We'd like to start rolling this out with rules_oci as soon as we can.

2024-02-20 05:47 UTC, thesayyn commented on src/test/java/com/google/devtools/build/lib/skyframe/TreeArtifactBuildTest.java
> -
Makes sense. Done. Added the tests back and changed them to assert those cases are still accepted.

2024-02-20 05:47 UTC, thesayyn commented
@tjgq Ready for another pass.

2024-02-20 13:06 UTC, tjgq approved these changes

2024-02-20 13:08 UTC, tjgq commented
@bazel-io fork 7.1.0

2024-02-21 11:15 UTC, closed without merging