Add cgroup startup option
bazelbuild/bazel pull request #21618
Opened 2024-03-08 09:12 UTC by AlessandroPatti

This options will have the server start in the user-specifed cgroup. This is useful when using the cgroup features in bazel and thus the server must be started in a user-writable cgroup.

2024-03-08 10:15 UTC, AlessandroPatti commented
cc @zhengwei143 since we discussed having an option to facilitate the setup

2024-06-07 11:25 UTC, AlessandroPatti commented
@zhengwei143 thoughts on this one?

2024-06-11 09:19 UTC, zhengwei143 commented
Atm I'm not sure this is the right way to go, it seems a little clunky to need to explicitly specify a cgroup path. Originally I had `systemd-run` in mind but then that's not always supported by default in all systems. Is the underlying issue of non-writable cgroups relevant / happening on your side?

2024-06-12 11:27 UTC, AlessandroPatti commented
@zhengwei143 yes, this happens all the time because cgroups are root-owned by default so bazel cannot create cgroups. The are three alternatives:
  - Start bazel as root
  - Make entire group hierarchy user-writable
  - Create a user-writable cgroup and launch bazel in there

The latter seems the best/safest option, and this flag helps achieving that

2024-06-19 08:44 UTC, AlessandroPatti commented
@zhengwei143 could you suggest changes to make this mergeable? It'd be nice to be able to just start bazel with the cgroup feature working without having to jump through hoops. How do you do this internally, do you rely on `systemd`?

2024-06-19 10:27 UTC, zhengwei143 commented
I don't think we necessarily want this in Bazel because this seems to me to be an environment issue. I'm not sure if there are other cases, but for me the issue I've identified is that the shell session is created in a root cgroup. As such, when Bazel is started up it inherits the same root cgroup.

Doing something like `systemd-run --user --scope bash` would probably create a new shell that runs in a user cgroup (and have Bazel's cgroup features working as intended) without needing to plumb in the `--cgroup_parent` on startup.

2024-07-02 15:49 UTC, AlessandroPatti commented
> I don't think we necessarily want this in Bazel because this seems to me to be an environment issue. I'm not sure if there are other cases, but for me the issue I've identified is that the shell session is created in a root cgroup. As such, when Bazel is started up it inherits the same root cgroup.
> 
> Doing something like `systemd-run --user --scope bash` would create a new shell that runs in a user cgroup (and _should_ have Bazel's cgroup features working as intended) without needing to plumb in the `--cgroup_parent` on startup.

True, that works, it is essentially what I am doing at the moment. However having to ensure all the shells that will run bazel are executed in the right cgroup is more painful than just adding `--cgroup_parent` in bazelrc

2024-07-02 16:07 UTC, zhengwei143 commented
> True, that works, it is essentially what I am doing at the moment. However having to ensure all the shells that will run bazel are executed in the right cgroup is more painful than just adding --cgroup_parent in bazelrc

Is there a default (fixed) user cgroup that you can use to specify in the bazelrc though? `/sys/fs/cgroup/user.slice/user-<uid>.slice/user@<uid>.service` seems to be an option, but I'm not sure that's what we'd want.

2024-07-02 16:11 UTC, AlessandroPatti commented
> > True, that works, it is essentially what I am doing at the moment. However having to ensure all the shells that will run bazel are executed in the right cgroup is more painful than just adding --cgroup_parent in bazelrc
> 
> Is there a default (fixed) user cgroup that you can use to specify in the bazelrc though? `/sys/fs/cgroup/user.slice/user-<uid>.slice/user@<uid>.service` seems to be an option, but I'm not sure that's what we'd want.

Not sure if there's one available out-of-the-box, but you could create one. A typical workflow would be have a user create a cgroup, add it to `~/.bazelrc`, never think about it again.

2024-07-20 08:40 UTC, AlessandroPatti commented
@zhengwei143 any thoughts on the above? Let me know if there's any change I can make to make this acceptable

2024-07-24 09:10 UTC, AlessandroPatti commented
> Left some comments, I don't see a good (automatic) way forward, in that case I'd be okay with having this functionality of specifying an already created cgroup.

Thanks @zhengwei143, I don't see your new comments, any chance you forgot to submit?

2024-07-24 09:13 UTC, zhengwei143 requested changes

2024-07-24 09:13 UTC, zhengwei143 commented
> > Left some comments, I don't see a good (automatic) way forward, in that case I'd be okay with having this functionality of specifying an already created cgroup.
> 
> Thanks @zhengwei143, I don't see your new comments, any chance you forgot to submit?

Ugh sorry, forgot again.

2024-07-25 17:18 UTC, AlessandroPatti commented on src/main/tools/daemonize.c
> +        char* opt = strtok(fs_mntops, ", ");
If was needed because otherwise `if (is_cpu || is_mem) {` below would always be true after we found the corresponding cgroup. Not relevant anymore

2024-07-25 17:18 UTC, AlessandroPatti commented on src/main/tools/daemonize.c
> +        if (is_cpu || is_mem) {
Good point, can easily be expanded. Done

2024-07-25 17:19 UTC, AlessandroPatti commented on src/main/tools/daemonize.c
> +        bool is_cpu, is_mem = false;
If was needed because otherwise `if (is_cpu || is_mem) {` below would always be true after we found the corresponding cgroup. Not relevant anymore

2024-07-31 08:03 UTC, zhengwei143 approved these changes
Looks great! I'll move ahead with importing this now.

2024-08-21 06:31 UTC, satyanandak commented
Hi @zhengwei143 ,  Since I can see that this PR has been approved, Please let us know whether gTech team should proceed with importing it. Thanks!"

2024-08-21 11:51 UTC, zhengwei143 commented
Hi, I've imported it internally but still trying to fix it to work internally.

2024-08-22 12:23 UTC, closed without merging

2024-09-05 09:22 UTC, AlessandroPatti commented
@zhengwei143 Thanks for importing this! In the final version however, the function now calls `WriteToFile`, which with crash if the file cannot be written. Instead, should we keep the follow to make it not fail as per documentation?
```
     FILE* procs = fopen(procs_path, "w");
     if (procs != NULL) {
         fprintf(procs, "%d", pid);
         fclose(procs);
     }
```

2024-09-06 17:40 UTC, tjgq commented
> @zhengwei143 Thanks for importing this! In the final version however, the function now calls `WriteToFile`, which with crash if the file cannot be written. Instead, should we keep the follow to make it not fail as per documentation?
> 
> ```
>      FILE* procs = fopen(procs_path, "w");
>      if (procs != NULL) {
>          fprintf(procs, "%d", pid);
>          fclose(procs);
>      }
> ```

(I was the one making the suggestion to check errors during the internal code review.)

What's the use case for this? It seems wrong to continue building normally if we failed to set up the cgroup; it gives the user false confidence that Bazel is operating as requested.