[7.2.0] Update buildozer to v7.1.1.1
bazelbuild/bazel pull request #22064
Opened 2024-04-19 19:04 UTC by iancha1992

Fixes https://github.com/bazelbuild/buildtools/pull/1263

Closes #22045.

PiperOrigin-RevId: 626307672
Change-Id: Ib088e73835ea3d7076976a9de4ab4207ff491b27

Commit https://github.com/bazelbuild/bazel/commit/7979dd6dfc56b6b61c3b6c65a806fe67c4fcd387

2024-04-19 22:54 UTC, iancha1992 commented
I've updated the lockfile... but there's errors with presubmits to update the lockfile. Please advise

cc: @Wyverald @meteorcloudy

2024-04-23 14:30 UTC, meteorcloudy requested changes

2024-04-23 14:30 UTC, meteorcloudy commented on MODULE.bazel.lock
> -        "bzlTransitiveDigest": "E2QiQlkDaM1FJ0uHgq2yD7CHDc3lTZRZe6qqYlEYiRI=",
I actually don't think this should be updated, can you please revert this ?

2024-04-23 14:31 UTC, meteorcloudy commented on MODULE.bazel.lock
> -        "bzlTransitiveDigest": "E2QiQlkDaM1FJ0uHgq2yD7CHDc3lTZRZe6qqYlEYiRI=",
Can you please do a `bazel clean --expunge`, it might because you were hitting https://github.com/bazel-contrib/bazel_features/issues/25

2024-04-24 10:08 UTC, meteorcloudy approved these changes

2024-04-24 10:41 UTC, merged