Provide "did you mean ...?" suggestions for unknown command-line options
bazelbuild/bazel pull request #22193
Opened 2024-04-30 11:56 UTC by fmeum

2024-05-20 17:33 UTC, fmeum commented
@justinhorvitz Gentle ping

2024-05-21 03:24 UTC, justinhorvitz requested changes
Sorry for the delay. This looks very useful!

2024-05-21 03:24 UTC, justinhorvitz commented on src/main/java/com/google/devtools/common/options/IsolatedOptionsData.java
> +  public Collection<Map.Entry<String, OptionDefinition>> getAllOptionDefinitions() {
Prefer declaring the immutable type (`ImmutableSet`).

2024-05-21 03:24 UTC, justinhorvitz commented on src/test/java/com/google/devtools/common/options/OptionsTest.java
Could you please also add test coverage for a positive boolean option and a non-boolean option?

2024-05-21 07:10 UTC, fmeum commented
@bazel-io fork 7.2.0

2024-05-21 11:38 UTC, justinhorvitz approved these changes

2024-05-22 19:40 UTC, closed without merging