Make local execution deduplication work with optional outputs
bazelbuild/bazel pull request #23296
Opened 2024-08-14 07:21 UTC by fmeum

This fixes failures such as the following when a spawn, e.g. a reduced Java compilation spawn, doesn't create an optional output:

```
java.io.FileNotFoundException: /private/var/tmp/_bazel_fmeum/507738cfc7e6cde00e4a0230e9aa0722/execroot/_main/bazel-out/_tmp/actions/remote/175.tmp (No such file or directory)
	at com.google.devtools.build.lib.unix.NativePosixFiles.lstat(Native Method)
	at com.google.devtools.build.lib.unix.UnixFileSystem.statInternal(UnixFileSystem.java:212)
	at com.google.devtools.build.lib.unix.UnixFileSystem.stat(UnixFileSystem.java:201)
	at com.google.devtools.build.lib.vfs.Path.stat(Path.java:290)
	at com.google.devtools.build.lib.vfs.FileSystemUtils.moveFile(FileSystemUtils.java:456)
	at com.google.devtools.build.lib.remote.RemoteExecutionService.moveOutputsToFinalLocation(RemoteExecutionService.java:878)
        ...
```

Also clean up temporary files in case of an exception.

2024-08-20 14:18 UTC, tjgq requested changes

2024-08-20 14:18 UTC, tjgq commented on src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java
> +        tmpPath.delete();
Add a try/catch so we don't throw an exception while handling another? (It's fine to silently ignore a failure to delete.)

2024-08-21 07:48 UTC, closed without merging

2024-08-21 07:56 UTC, fmeum commented
@bazel-io fork 7.4.0

2024-10-11 21:04 UTC, iancha1992 commented
The changes in this PR have been included in [Bazel 7.4.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.4.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=7.4.0rc1`. Thanks!