Add //src/tools/execlog:converter to docs
bazelbuild/bazel pull request #23373
Opened 2024-08-20 21:26 UTC by keith

This was mentioned in
https://blog.bazel.build/2024/04/01/bazel-q1-2024-community-update.html but not in the docs

2024-08-21 09:37 UTC, tjgq requested changes

2024-08-21 09:37 UTC, tjgq commented on site/en/remote/cache-remote.md
> +must first convert to the original format using the
s/original/binary or json/

2024-08-21 19:29 UTC, keith commented on site/en/remote/cache-remote.md
> +must first convert to the original format using the
done!

2024-08-22 11:08 UTC, tjgq approved these changes

2024-08-23 15:31 UTC, closed without merging