Use `--experimental_java_classpath=bazel` by default
bazelbuild/bazel pull request #23384
Opened 2024-08-21 18:57 UTC by fmeum

2025-05-16 15:04 UTC, fmeum commented
@cushon There is an interesting test failure on Windows:
```
java.io.IOException: C:/tmp/bazel_root_nfkp8n/b6wml6ky/bazel-workers/Javac-multiplex-worker-1-workdir/_main/__sandbox/1/_main/external/rules_java++toolchains+remotejdk11_win/lib/jrt-fs.jar (Permission denied)
	at com.google.devtools.build.lib.windows.WindowsFileSystem.delete(WindowsFileSystem.java:63)
	at com.google.devtools.build.lib.vfs.Path.delete(Path.java:614)
	at com.google.devtools.build.lib.sandbox.SandboxHelpers.cleanRecursively(SandboxHelpers.java:427)
	at com.google.devtools.build.lib.sandbox.SandboxHelpers.cleanRecursively(SandboxHelpers.java:432)
	at com.google.devtools.build.lib.sandbox.SandboxHelpers.cleanRecursively(SandboxHelpers.java:432)
	at com.google.devtools.build.lib.sandbox.SandboxHelpers.cleanRecursively(SandboxHelpers.java:432)
	at com.google.devtools.build.lib.sandbox.SandboxHelpers.cleanRecursively(SandboxHelpers.java:432)
	at com.google.devtools.build.lib.sandbox.SandboxHelpers.cleanExisting(SandboxHelpers.java:313)
	at com.google.devtools.build.lib.sandbox.SandboxHelpers.cleanExisting(SandboxHelpers.java:270)
	at com.google.devtools.build.lib.worker.SandboxedWorkerProxy.prepareExecution(SandboxedWorkerProxy.java:89)
...
```

It looks like JavaBuilder keeps `--system` runtime files open after it is done with a compilation. Do you happen to know what I would need to change to fix that? Happy to dig into it myself if you don't.

2025-05-23 11:27 UTC, hvadehra requested changes

2025-05-23 11:27 UTC, hvadehra commented on src/test/shell/bazel/bazel_java_test.sh
> +    >& $TEST_log || fail "build succeeded"
should this be "build failed"?

2025-05-23 12:49 UTC, hvadehra approved these changes

2025-06-17 09:41 UTC, fmeum commented
@hvadehra Friendly ping, does this lack the "awaiting-merge" label or did this turn out to be hard to merge internally?

2025-06-18 07:42 UTC, closed without merging