Do not fail if cgroups cannot be written
bazelbuild/bazel pull request #23540
Opened 2024-09-06 16:45 UTC by AlessandroPatti

From comment https://github.com/bazelbuild/bazel/pull/21618#issuecomment-2331031439: as per documentation
> It is not an error if the specified cgroup is not writable for one or more of the controllers

However WriteFile will fail if the file cannot be written, so it cannot be used in this context

2024-09-11 12:09 UTC, tjgq commented
@AlessandroPatti Can you answer my question in https://github.com/bazelbuild/bazel/pull/21618#issuecomment-2334532889? It's unclear to me whether we should move forward with this PR, or simply amend the flag description to match the current implementation.

2024-10-03 07:31 UTC, AlessandroPatti commented
> @AlessandroPatti Can you answer my question in [#21618 (comment)](https://github.com/bazelbuild/bazel/pull/21618#issuecomment-2334532889)? It's unclear to me whether we should move forward with this PR, or simply amend the flag description to match the current implementation.

@tjgq sorry for the delay here. From [previous conversations](https://github.com/bazelbuild/bazel/pull/21322#discussion_r1494660336), handle misconfiguration gracefully and proceed with the build was preferable. I found it to be the case for our internal use-case as well, and I think in the case of this flag it is even more so, since the purpose of it is to just add it to `.bazelrc`, but open to discussion. Maybe a warning might do here?

2025-02-11 12:27 UTC, AlessandroPatti commented
@tjgq thoughts on this? cc @zhengwei143

2025-02-12 10:33 UTC, zhengwei143 commented
> From https://github.com/bazelbuild/bazel/pull/21322#discussion_r1494660336, handle misconfiguration gracefully and proceed with the build was preferable. I found it to be the case for our internal use-case as well, and I think in the case of this flag it is even more so, since the purpose of it is to just add it to .bazelrc, but open to discussion. Maybe a warning might do here?

We've recently run into this issue internally as well (cc @bigelephant29), and I'm for handling failures gracefully here. 

Unfortunately it seems that there is too much out of our control w.r.t users' environment that can create issues with setting up cgroups. This makes rolling out this flag problematic. The goal of cgroups in Blaze is for us to have better control over resource management, the absence of that just means that we are reverting back to our previous (less ideal) mechanisms in resource management; I'd rather we not fail builds here. I don't think individual users would be explicitly setting `--experimental_cgroup_parent` to optimize their builds, this would probably be set at a bazelrc level to optimize builds (if possible).

I think what we need are mechanisms to identify that a spawn was not created with a cgroup when it was intended to, perhaps a simple log would do.

2025-03-14 10:52 UTC, AlessandroPatti commented
@zhengwei143 looks like we are aligned on general direction. I've added a debug log line when the cgroup cannot be written to. Can you give another pass?

2025-03-24 15:47 UTC, zhengwei143 commented on src/main/tools/daemonize.cc
> +        fprintf(procs, "%d", pid);
Could you add checks and additional logging to `fprintf` and `fclose` similar to lines 94 & 97 to indicate that we failed to start the server in the specified cgroup?

2025-04-09 08:18 UTC, bigelephant29 commented
@AlessandroPatti Let's wait for @zhengwei143 to be back. Looks good to me overall.

In the meantime, we're going to release a new startup option to support starting the bazel server in a user cgroup.

See f17f91005cf748d9a446091fac4e982e5bd9e8e0.

Is `systemd` available in your environment?

If so, please try out `--experimental_run_in_user_cgroup` and you won't need to set up a user cgroup manually anymore. Just keep in mind that this has environmental dependency so it might not work for every user.

I'm also curious about how you manually set up cgroups in your local. Do you have any instructions/documents about it? Thanks!

2025-04-16 10:49 UTC, zhengwei143 approved these changes

2025-04-16 12:34 UTC, zhengwei143 requested changes
BazelCI seems to be failing, could you have a quick look?

2025-04-24 20:58 UTC, closed without merging

2025-05-07 13:59 UTC, bigelephant29 commented
> In the meantime, we're going to release a new startup option to support starting the bazel server in a user cgroup.
> 
> See [f17f910](https://github.com/bazelbuild/bazel/commit/f17f91005cf748d9a446091fac4e982e5bd9e8e0).
> 
> Is `systemd` available in your environment?
> 
> If so, please try out `--experimental_run_in_user_cgroup` and you won't need to set up a user cgroup manually anymore. Just keep in mind that this has environmental dependency so it might not work for every user.
> 
> I'm also curious about how you manually set up cgroups in your local. Do you have any instructions/documents about it? Thanks!

@AlessandroPatti any updates regarding this? This was included in 8.2.0.