Add support for an allowlist to `oneversion`
bazelbuild/bazel pull request #23609
Opened 2024-09-12 14:36 UTC by fmeum

2024-09-12 15:24 UTC, cushon requested changes
Thanks very much!

2024-09-12 15:24 UTC, cushon commented on src/tools/one_version/allowlist.cc
> +  }
This segfaults if it's given an allowlist that doen't have at least two records on each line, could you add some rudimentary error handling here?

Also I have a slight preference for moving the parsing logic to main, to keep MapAllowlist agnostic of the allowlist format we're using here.

2024-09-12 15:34 UTC, cushon approved these changes

2024-09-13 19:44 UTC, closed without merging

2024-09-13 21:47 UTC, fmeum commented
@keertk Could you create a new java_tools release?