Performance optimization for isSymbolicLink() calls on Windows
bazelbuild/bazel pull request #24047
Opened 2024-10-22 13:30 UTC by AlexanderGolovlev

Current implementation for WindowsFileSystem.isSymbolicLink() makes unnecessary system calls which significantly affect the performance. Original code goes through the following:
- AbstractFileSystemWithCustomStat.isSymbolicLink
  - WindowsFileSystem.stat
    - WindowsFileSystem.getIoFile
    - JavaIoFileSystem.getNioPath
    - Files.readAttributes
    - WindowsFileSystem.fileIsSymbolicLink
    - WindowsFileOperations.getLastChangeTime
This implementation skips most of them.

2024-10-22 14:19 UTC, fmeum commented
Nice find!

2024-10-22 14:23 UTC, tjgq reviewed
The whole point of `AbstractFileSystemWithCustomStat` is to derive the `isFoo` methods from a `stat` implementation, so while this PR does seem worthwhile for the performance benefits, the end result seems a bit convoluted. I wonder if we could instead do the following:

- Have `JavaIoFileSystem` extend `AbstractFileSystem` instead of `AbstractFileSystemWithCustomStat`, with the `isFoo` methods implemented as `Files.isFoo`
- in `WindowsFileSystem`, override `isSymbolicLink` as currently implemented by your PR

But feel free to push back if my suggested refactoring is more difficult than it appears at first sight.

2024-10-24 17:27 UTC, AlexanderGolovlev commented
@tjgq , with your comment I've got an idea that we could try to optimize other `isFoo` methods derived from `stat`, in addition to `isSymbolicLink`. This is done in my second commit and is based on a "lazy" implementation for some `stat` methods. This should save us at least 1/3 of time for any `isFoo` call, and 2/3 of time for some methods like `getFileSize`.
However, I'm not sure about replacing the `AbstractFileSystemWithCustomStat` by `AbstractFileSystem`. This will require implementing the `isFoo` methods not only in `JavaIoFileSystem`, but also in `WindowsFileSystem`. This will cause duplication of code and excessive complexity.

2024-10-24 18:44 UTC, tjgq requested changes
I like this version! Just a couple of minor comments.

2024-10-24 18:44 UTC, tjgq commented on src/main/java/com/google/devtools/build/lib/windows/WindowsFileSystem.java
> +          volatile Boolean isSymbolicLink;
Let's mark this `@Nullable` and append a comment `// null if not yet known` to make the convention clear.

2024-10-24 18:44 UTC, tjgq commented on src/main/java/com/google/devtools/build/lib/windows/WindowsFileSystem.java
> +            if (isSymbolicLink == null) { isSymbolicLink = !followSymlinks && fileIsSymbolicLink(file); }
Nit: the `if` body should be on its own line.

2024-10-24 18:44 UTC, tjgq commented on src/main/java/com/google/devtools/build/lib/windows/WindowsFileSystem.java
> +            if (lastChangeTime == -1) { lastChangeTime = WindowsFileOperations.getLastChangeTime(getNioPath(path).toString(), followSymlinks); }
Same as above.

2024-10-24 18:45 UTC, tjgq commented
> @tjgq , with your comment I've got an idea that we could try to optimize other `isFoo` methods derived from `stat`, in addition to `isSymbolicLink`. This is done in my second commit and is based on a "lazy" implementation for some `stat` methods. This should save us at least 1/3 of time for any `isFoo` call, and 2/3 of time for some methods like `getFileSize`. However, I'm not sure about replacing the `AbstractFileSystemWithCustomStat` by `AbstractFileSystem`. This will require implementing the `isFoo` methods not only in `JavaIoFileSystem`, but also in `WindowsFileSystem`. This will cause duplication of code and excessive complexity.

That's a fair point; let's keep it an `AbstractFileSystemWithCustomStat`, then.

2024-10-25 09:36 UTC, tjgq approved these changes

2024-10-29 11:29 UTC, closed without merging