Implement `debugPrint` for built-in file providers
bazelbuild/bazel pull request #24156
Opened 2024-10-31 10:51 UTC by fmeum

Simplifies `print` style debugging.

2024-12-09 15:50 UTC, comius commented
cc @brandjon @tetromino 
You might have an opinion about this as well...

2024-12-09 17:31 UTC, brandjon commented
If it doesn't expose non-hermetic / non-deterministic information that we don't want Starlark users to introspect on, then it should be safe for `str()`/`repr()` and not just `print()`.

But limiting it to `print()` is less of a breaking change, if that's what you're worried about. Still, I think a `str()` breakage in a provider isn't that big a deal.

2024-12-14 15:29 UTC, fmeum commented
> I'd go for a more Starlark representation, printing those providers as if they were implemented in starlark.

That's a good point. I've modified the methods to use `struct` syntax, including alphabetic ordering of keys. A positive side effect of this is that you can use `buildifier` to prettify the output if you want to.

2025-01-24 08:37 UTC, comius requested changes

2025-01-24 08:37 UTC, comius commented on src/main/java/com/google/devtools/build/lib/analysis/FileProvider.java
> +    printer.append("file_provider(files_to_build = ");
For consistency with FilesToRunProvider, this should probably be "FileProvider".

I'd prefer more Starlark names ending with Info, but they aren't used at the moment anywhere.

2025-01-24 08:37 UTC, comius commented on src/main/java/com/google/devtools/build/lib/analysis/Runfiles.java
> +    printer.append("runfiles(empty_files = ");
nit: "Runfiles" instead of "runfiles"

2025-01-24 08:40 UTC, comius commented
> That's a good point. I've modified the methods to use struct syntax, including alphabetic ordering of keys. A positive side effect of this is that you can use buildifier to prettify the output if you want to.

Nice.

> I noticed that the providers that derive from StructImpl don't print their type (e.g. OutputGroupInfo is just a struct(...)). This has some benefits in terms of consistency, but it also loses information. What would you prefer?

My preference would be to print out the Name in all cases (either native or Starlark). I don't know what's current state.
I'm leaning more to Name, because it matters, i.e. `OutputGroupInfo(a=["x"]) != struct(a =["x"])`

2025-01-31 07:53 UTC, comius approved these changes

2025-01-31 07:59 UTC, fmeum commented
@bazel-io fork 8.1.0

2025-01-31 10:07 UTC, lberki commented
(late to the party)

Yes, I do have an opinion, which is that this is a good thing :)

2025-01-31 19:53 UTC, closed without merging