Fix more Unicode bugs
bazelbuild/bazel pull request #24182
Opened 2024-11-04 13:09 UTC by fmeum

2024-11-05 15:56 UTC, fmeum commented
@tjgq This is stacked on #24010, but the last commit is new and ready for review.

2024-11-07 17:58 UTC, tjgq commented
@fmeum Mind rebasing before I review?

2024-11-07 18:22 UTC, fmeum commented
@bazel-io fork 8.0.0

2024-11-08 11:01 UTC, tjgq requested changes

2024-11-08 11:01 UTC, tjgq commented on src/test/shell/bazel/starlark_repository_test.sh
> +    # äöüÄÖÜß in UTF8
Nit: "UTF-8" (also below)

2024-11-08 11:01 UTC, tjgq commented on src/test/shell/integration/starlark_dependency_pruning_test.sh
> +    # äöüÄÖÜß in UTF8
Nit: "UTF-8" (also below)

2024-11-11 13:48 UTC, tjgq commented
> @tjgq Thanks for the review, it helped me find and fix more issues.
> 
> I noticed that there are a bunch of `FileSystemUtils` methods that read and write files in different encodings. I could clean that up in a follow-up PR or as part of this PR, as you prefer.

I'd prefer a separate PR, thanks!

2024-11-11 14:10 UTC, fmeum commented
> @fmeum it looks like there's an issue with .netrc parsing? (see failed tests)

Should be fixed now

2024-11-11 17:29 UTC, fmeum commented
@meteorcloudy Compiling a `cc_library` that depends on a header file with non-ASCII characters in its name results in this kind of error:

```
ERROR: C:/b/absmfft5/execroot/_main/_tmp/925c5432c7427d85ec55d631e57c838b/workspace/pkg/BUILD:5:10: Compiling pkg/bin.cc failed: undeclared inclusion(s) in rule '//pkg:bin':
this rule is missing dependency declarations for the following files included by 'pkg/bin.cc':
  'pkg/„”Ž™šá??.h'
```

The raw bytes of the file name are `112, 107, 103, 47, -124, -108, -127, -114, -103, -102, -31, 63, 63, 46, 104`, which indicates that the output of MSVC is in the OEM codepage 437. This is hinted at [here](https://learn.microsoft.com/en-gb/cpp/build/reference/unicode-support-in-the-compiler-and-linker?view=msvc-170#output). Do you know of a way to force `cl.exe` to output Unicode when it's not running in a console (or, alternatively, to have it think it's running in a console)?

2024-11-12 09:10 UTC, meteorcloudy commented
Maybe this one https://learn.microsoft.com/en-gb/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170?

2024-11-12 10:21 UTC, fmeum commented
> Maybe this one https://learn.microsoft.com/en-gb/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170?

That didn't help :-(

2024-11-12 11:41 UTC, fmeum commented
I have given up on getting `cl.exe` to work. Users could presumably still do this themselves by switching their system code page to UTF-8.

2024-11-14 18:10 UTC, fmeum commented
@tjgq Rebased onto master.

2024-11-15 12:24 UTC, fmeum commented
@bazel-io fork 8.0.0

2024-11-18 23:07 UTC, iancha1992 commented
@fmeum can you please resolve the conflicts? Thanks!

2024-11-19 18:35 UTC, fmeum commented
@iancha1992 Rebased

2024-11-19 20:47 UTC, closed without merging

2024-11-22 22:59 UTC, iancha1992 commented
The changes in this PR have been included in [Bazel 8.0.0 RC3](https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc3). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=8.0.0rc3`. Thanks!

2024-11-26 15:53 UTC, meteorcloudy commented
Looks like this is again rolled-back in https://github.com/bazelbuild/bazel/commit/e27ab916aaa6b12f2be4e463a54ef49965cc04a7

@tjgq @katre Can you provide some details on the issue?

2024-11-26 15:55 UTC, katre commented
@tjgq has a better understanding of the cause than I do (I just noticed the failures and initiated the rollback).

2024-11-26 16:00 UTC, tjgq commented
See b/381060195 for some details. I'm fairly confident that the root cause was in Google code, not Bazel code, and I expect the fix to be very localized. So, absent evidence that it breaks anything externally, I'd recommend sticking with the cherry-pick for now.