Fix Unicode encoding issues in Bazel's use of Starlark
bazelbuild/bazel pull request #24417
Opened 2024-11-20 17:06 UTC by fmeum

2025-01-15 23:04 UTC, tetromino commented
To be clear, are all string values that Bazel currently passes to split encoded consistently as raw-UTF-bytes? Or is there a possibility that we have a mixture of encodings?

2025-01-16 08:44 UTC, fmeum commented
> To be clear, are all string values that Bazel currently passes to split encoded consistently as raw-UTF-bytes? Or is there a possibility that we have a mixture of encodings?

All strings fed into and obtained from Starlark, in fact every string retained by Bazel, should now be raw UTF-8 bytes. Strings with other encodings are only produced or consumed at I/O boundaries such as in `FileSystem` implementations.

2025-02-10 21:43 UTC, tetromino commented on src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java
> +            .setBool(StarlarkSemantics.INTERNAL_BAZEL_ONLY_UTF_8_BYTE_STRINGS, true)
Probably a merge error? Please remove

2025-02-10 23:21 UTC, fmeum commented on src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java
> +            .setBool(StarlarkSemantics.INTERNAL_BAZEL_ONLY_UTF_8_BYTE_STRINGS, true)
Yes, removed

2025-02-14 20:59 UTC, brandjon requested changes
I didn't review json stuff, leaving that to Tiago.

I'm OOO the coming week. Tiago can sign off on changes made as per my comments during that time.

2025-02-14 20:59 UTC, brandjon commented on src/main/java/net/starlark/java/eval/StarlarkSemantics.java
> +      if (map.isEmpty()) {
Nit: It looks like this just micro-optimizes away the few lines it would take `copyOf()` to allocate an iterator and realize that the map is empty. But constructing a `StarlarkSemantics` doesn't happen very often. Delete?

2025-02-14 20:59 UTC, brandjon commented on src/main/java/net/starlark/java/eval/StarlarkSemantics.java
> +      "-internal_bazel_only_utf_8_byte_strings";
Careful, the leading `-` or `+` must match the default value specified in the `@Option`. Change to `"+internal_bazel_only_utf_8_byte_strings".

2025-02-14 20:59 UTC, brandjon commented on src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java
> +      documentationCategory = OptionDocumentationCategory.UNDOCUMENTED,
Fine to leave undocumented for users, but please add a docstring for our own benefit.

2025-02-14 20:59 UTC, brandjon commented on src/main/java/net/starlark/java/eval/StringModule.java
> +  private static final CharMatcher ASCII_WHITESPACE =
Add javadoc indicating that we use this when using the latin-1 hack in order to avoid triggering on utf-8 code units above 0x7f.

2025-02-14 20:59 UTC, brandjon commented on src/main/java/net/starlark/java/eval/StringModule.java
> +        // TODO: This doesn't work correctly for non-ASCII characters in charsOrNone if using UTF-8
Nit: It's a little ambiguous what the comment is saying, how about:

> When using the latin-1 hack, each utf-8 code unit is stored as a distinct string element. To avoid matching an element that doesn't correspond to a whole code point, we exclude anything that's not in the ASCII range.

2025-02-14 20:59 UTC, brandjon commented on src/main/java/net/starlark/java/eval/Starlark.java
> +        StringModule.INSTANCE.stripSemantics(lines.get(0), NONE, StarlarkSemantics.DEFAULT);
Relying on `StarlarkSemantics.DEFAULT` is often a code smell. In this case, it means that flipping the flag in any way that doesn't also change its hardcoded default value will create an inconsistency between how U+A0 is handled in docstring content vs how the .bzl gets decoded.

The proper fix would require taking a StarlarkSemantics as an argument to this method. That looks like a nuisance, so it's fine to add a TODO.

2025-02-14 20:59 UTC, brandjon commented on src/test/java/net/starlark/java/eval/testdata/sorted.star
>  # The first compares greater than the second.
Update comment.

2025-02-14 20:59 UTC, brandjon commented on src/test/java/net/starlark/java/eval/BUILD
> +    name = "ScriptTest_Latin1",
I'm slightly worried about redundantly rerunning non-string-related tests. Can we filter this down to just those test suites that actually are affected by encoding/string behavior?

2025-02-19 17:12 UTC, fmeum commented on src/main/java/net/starlark/java/eval/StarlarkSemantics.java
> +      if (map.isEmpty()) {
It's also meant to make equality checks (such as in `net.starlark.java.eval.CallUtils#getStarlarkClassDescriptor`) between "default" semantics instances as fast as possible. It's still a micro-optimization, but it's not just relevant for construction.

2025-02-19 17:21 UTC, fmeum reviewed
@tjgq Could you take a look?

2025-02-19 17:21 UTC, fmeum commented on src/main/java/net/starlark/java/eval/StarlarkSemantics.java
> +      "-internal_bazel_only_utf_8_byte_strings";
Usually yes, but this case is special: We want Starlark to keep using regular Java strings outside Bazel, so this necessarily needs to be off by default. This is also why I had to change the `checkDefaultsMatch` test.

2025-02-19 17:21 UTC, fmeum commented on src/test/java/net/starlark/java/eval/BUILD
> +    name = "ScriptTest_Latin1",
The test passes in 0.8s on my machine. I could explicitly list all tests that are affected at this point in time, but I'm pretty certain that I would miss some - not even taking into account that the list is bound to become stale over time. Given how subtle the difference is, I have a strong preference for just running all tests twice.

2025-02-19 19:28 UTC, fmeum commented on src/main/java/net/starlark/java/eval/StarlarkSemantics.java
> +      "-internal_bazel_only_utf_8_byte_strings";
Copybara and presumably other Google-internal tools use Starlark and probably don't want Bazel's internal string encoding. Even though it doesn't live in its own repo, the Java Starlark implementation also appears to be somewhat general purpose, which probably means that its defaults should work well outside Bazel.

Does the tool at Google not go through flag parsing in the sense that each Blaze option is left at its default? In that case this should still work just fine.

2025-02-19 19:43 UTC, tjgq commented on src/main/java/net/starlark/java/eval/StarlarkSemantics.java
> +      "-internal_bazel_only_utf_8_byte_strings";
It doesn't know about flags at all - it instantiates a `StarlarkSemantics` directly. Let me ask someone more familiar with that code on how to proceed.

2025-02-19 19:55 UTC, tjgq commented on src/main/java/net/starlark/java/eval/StarlarkSemantics.java
> +      "-internal_bazel_only_utf_8_byte_strings";
Let me put it this way - the way to not overthink this is to:

1. Submit this PR with a default value of `false` (which is hopefully a no-op both for Bazel and other code calling into the Starlark interpreter)
2. Flip the default to `true` in google3 flag via the global blazerc (I can do this, although we'll have to wait ~2 weeks for a Blaze release)
3. Flip the codebase default to `true`

The advantage here is that, at the time (2) is done, we can also arrange for our internal tool to override the option appropriately in its manually constructed `StarlarkSemantics` (which we always have to do whenever a load-affecting flag is overridden in the global blazerc). While we could technically do the same at step (1), it would require us to override an internal test to check that the `+`/`-` prefix matches the default for every flag, which I'd strongly prefer not to do.

Is the plan above viable?  In particular, is it true that a default of `false` would be a no-op for everyone calling into this code? If not, I can dig further for a solution.

2025-02-19 20:02 UTC, tjgq commented on src/main/java/net/starlark/java/eval/StarlarkSemantics.java
> +      "-internal_bazel_only_utf_8_byte_strings";
Ugh, nevermind - what I wrote above makes no sense, because step (3) gets us back to a state where the flag default doesn't match the `-`/`+` prefix. I'll have to ask someone else.

2025-02-19 21:08 UTC, tjgq commented on src/main/java/net/starlark/java/eval/StarlarkSemantics.java
> +      "-internal_bazel_only_utf_8_byte_strings";
Can you walk me through what would change (say) in Copybara if we were to replace `-` with `+` in the line above?

I don't see how this prefix affects anything other than `BuildLanguageOptions.toStarlarkSemantics`, and `BuildLanguageOptions` is not a part of the Starlark interpreter. Specifically for Copybara, I don't `toStarlarkSemantics` being called anywhere in its codebase, though I do see occurrences of `StarlarkSemantics.DEFAULT` (which is not affected by the `+`/`-`).

2025-02-19 21:58 UTC, fmeum commented on src/main/java/net/starlark/java/eval/StarlarkSemantics.java
> +      "-internal_bazel_only_utf_8_byte_strings";
`StarlarkSemantics.DEFAULT` is affected by the sign: with it, each Starlark function that queries the semantics for the flag would see it as enabled. But that's not what we want, it should only be enabled in Bazel.

2025-02-19 22:26 UTC, tjgq commented on src/main/java/net/starlark/java/eval/StarlarkSemantics.java
> +      "-internal_bazel_only_utf_8_byte_strings";
Alright, after an internal discussion and a lot of confusion on my part (sorry for the stupid questions), I think we have figured out a way to move forward. I'll give importing this a try tomorrow to check that it works.

2025-02-20 14:40 UTC, tjgq requested changes

2025-02-20 15:03 UTC, fmeum commented on src/test/java/net/starlark/java/eval/testdata/json.star
> +assert_eq(json.encode("😹"[:1]), '"�"') if not _utf8_byte_strings else None # invalid UTF-16 -> replacement char U+FFFD
They are not:
```
./src/test/java/net/starlark/java/eval/testdata/json.star:29:1: if statements are not allowed at the top level. You may move it inside a function or use an if expression (x if condition else y).
```

2025-02-20 18:20 UTC, fmeum commented on src/test/java/net/starlark/java/eval/testdata/json.star
This was both a nightmare (see the comments I added) and super helpful as the previous implementation had a number of bugs, including for the existing UTF-16 string case. PTAL.

2025-02-21 16:36 UTC, tjgq approved these changes
Importing. Since we're changing `json.decode` behavior in some corner cases, there's a small but nonzero chance of a rollback, so I advise waiting for a few days before building on top of this.

2025-02-21 16:38 UTC, fmeum commented
@bazel-io fork 8.2.0

2025-03-04 16:02 UTC, closed without merging