Fix even more Unicode bugs
bazelbuild/bazel pull request #24457
Opened 2024-11-22 13:01 UTC by fmeum

2024-11-22 19:53 UTC, fmeum commented
I suspect that the RBE failure is due to the remote execution environment not having the `C.UTF-8` locale installed which is forced for Java compilation actions. Would it be possible to add it?

2024-11-22 20:04 UTC, tjgq commented
> I suspect that the RBE failure is due to the remote execution environment not having the `C.UTF-8` locale installed which is forced for Java compilation actions. Would it be possible to add it?

I think that entails creating a new docker image for RBE (or finding a suitable existing one). @coeuvre, do you know how to do this?

If this is blocking for 8.0.0, I suggest finding a way to either detect the existence of the locale in the test, or disable it when on RBE.

2024-11-22 21:47 UTC, fmeum commented
The test is failing on other platforms, so I'll look into that. It's not a hard blocker for 8.0.0, it can equally well go into 8.1.0.

2024-11-25 15:30 UTC, fmeum commented
This needs a fix in rules_java to properly set a UTF-8 environment for bootstrap actions: https://github.com/bazelbuild/rules_java/pull/243

2025-01-18 10:56 UTC, fmeum commented
@hvadehra Do you know whether rules_java 8.7.1 ships java_tools that include https://github.com/bazelbuild/bazel/commit/a37d288b80d8b51e96f13b3a7bce82d54dfe7ff9? Is there a way to tell which Bazel commit a given rules_java release was based on for java_tools?

2025-01-20 09:02 UTC, hvadehra commented
The README.md in the java_tools zip archives has provenance info. Looks like v13.14 was built at 7d2509e8a4e27810143b462bd0f2cfc21b48193b

2025-01-20 09:33 UTC, fmeum commented
> The README.md in the java_tools zip archives has provenance info. Looks like v13.14 was built at [7d2509e](https://github.com/bazelbuild/bazel/commit/7d2509e8a4e27810143b462bd0f2cfc21b48193b)

That's convenient. I can now tell that it doesn't include the required a37d288b80d8b51e96f13b3a7bce82d54dfe7ff9.

@hvadehra I filed https://github.com/bazelbuild/rules_java/issues/265 as a replacement for https://github.com/bazelbuild/rules_java/issues/250.

2025-02-05 20:21 UTC, fmeum commented
@tjgq I had to resolve a non-trivial merge conflict with master.

2025-02-06 21:03 UTC, fmeum commented
CI is finally green, thanks to everyone who was cutting releases (@iancha1992 @hvadehra)!

2025-02-06 21:05 UTC, fmeum commented
@bazel-io fork 8.1.0

2025-02-07 16:12 UTC, tjgq requested changes

2025-02-07 20:25 UTC, fmeum commented on src/main/java/com/google/devtools/build/lib/vfs/FileSystem.java
> +   * the local file system.
I could hand-roll an implementation that creates directories under `/tmp`, assuming that any non-Unix system would use the current implementation. Would that address your concern?

2025-02-10 08:45 UTC, fmeum commented on src/main/java/com/google/devtools/build/lib/vfs/FileSystem.java
> +   * the local file system.
I added an implementation that just delegates to other methods. It won't be safe to use on multi-user systems, but I guess your alternative implementations don't care about that?

2025-02-11 11:12 UTC, tjgq commented on src/main/java/com/google/devtools/build/lib/vfs/FileSystem.java
> +   * the local file system.
Yeah, I think this is fine. But, don't we also need to override this method in `RemoteActionFileSystem`? Otherwise, it's going to use the non-secure version instead of delegating to the local filesystem (which is able to use the secure one).

Can you also add a unit test for this method in `FileSystemTest.java`?

2025-02-11 11:13 UTC, tjgq commented on src/main/java/com/google/devtools/build/lib/vfs/FileSystem.java
> +   * the local file system.
(Nevermind about the unit test, I see it's already there)

2025-02-11 13:25 UTC, fmeum commented on src/main/java/com/google/devtools/build/lib/vfs/FileSystem.java
> +   * the local file system.
Discussed offline, I dropped the JDK implementation as a result

2025-02-11 14:02 UTC, tjgq approved these changes

2025-02-13 15:23 UTC, closed without merging

2025-02-14 12:48 UTC, tjgq commented
@fmeum Heads up that this will be rolled back - it broke `bazel info build-language` (I think it's because the changes in `InfoItem` made it incompatible with binary output)

2025-02-16 14:34 UTC, fmeum commented
@tjgq Thanks for the info, I sent https://github.com/bazelbuild/bazel/pull/25291 with the reland.