Remove autoload warnings and improve errors
bazelbuild/bazel pull request #24601
Opened 2024-12-06 22:00 UTC by fmeum

This reduces noise while giving users more actionable information when they actually use a symbol that failed to autoload.

Fixes #23929 
Fixes #24597

2024-12-06 22:01 UTC, fmeum commented
FYI @keith 

Based on the test, it looks like `apple_support` isn't loaded as `bazel_build_apple_support` in WORKSPACE mode. Should we also fix that?

2024-12-06 22:01 UTC, fmeum commented
@bazel-io flag

2024-12-06 22:02 UTC, keith commented
huh i hadn't seen that test at all..im not sure

2024-12-06 22:05 UTC, fmeum commented
The same may be true for protobuf.

2024-12-09 12:03 UTC, comius requested changes

2024-12-09 12:03 UTC, comius commented on src/main/java/com/google/devtools/build/lib/packages/AutoloadSymbols.java
>          missingRepositories.add(label.getRepository().getName());
The entire variable `missingRepositories` may now be removed.

2024-12-09 12:09 UTC, comius commented
I tried adding `@apple_support` to the --incompatible_autoload_externally, but I had some problems with it. I can't find a PR with that change. Trying to remember, the problems might have been due to apple_common, that doesn't exist anywhere (and won't). But autoloading all 3 XCode rules could work.

2024-12-09 12:16 UTC, fmeum commented
@comius I think I'm close to getting something to work, I'll push an update soon.

2024-12-09 12:53 UTC, fmeum commented
@comius Protobuf depends on `apple_support` via its WORKSPACE macro (https://github.com/protocolbuffers/protobuf/blob/2d4414f384dc499af113b5991ce3eaa9df6dd931/protobuf_deps.bzl#L158-L162), but not via its MODULE.bazel file. The WORKSPACE version it loads doesn't have the autoloaded symbols.

2024-12-09 15:00 UTC, fmeum commented on src/test/shell/integration/incompatible_autoload_externally_test.sh
> +# TODO: protobuf's WORKSPACE macro has an unnecessary dependency on build_bazel_apple_support.
This should be fixed at some point, but doesn't matter too much right now as `apple_support` doesn't have any of the Starlarkified rules yet.

2024-12-10 19:23 UTC, iancha1992 commented
@bazel-io fork 8.1.0

2024-12-11 13:56 UTC, fmeum commented
@bazel-io fork 8.0.1

2024-12-19 20:15 UTC, fmeum commented
@comius Friendly ping

2025-01-07 10:15 UTC, comius approved these changes

2025-01-08 10:03 UTC, closed without merging